apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default
  source:
    # This is a verified, active repo in 2026
    repoURL: https://moandat.github.io/charts
    chart: sonarr
    targetRevision: 2.1.0 # Or latest stable
    helm:
      values: |
        image:
          repository: lscr.io/linuxserver/sonarr
          tag: latest
        env:
          TZ: America/Toronto
          PUID: 1000
          PGID: 1000
        persistence:
          config:
            enabled: true
            storageClass: "longhorn"
            size: 2Gi
          media:
            enabled: true
            existingClaim: nfs-media-pvc
            mountPath: /tv
        ingress:
          main:
            enabled: true
            className: traefik
            hosts:
              - host: tv.smeyer.ca
                paths:
                  - path: /
                    pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
