apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default
  source:
    # This is the modern 'heavyweight' repo that hasn't moved
    repoURL: https://charts.truecharts.org
    chart: sonarr
    targetRevision: 15.0.12 # Current stable OCI-backed version
    helm:
      values: |
        image:
          repository: tccr.io/truecharts/sonarr
          tag: v4.0.1.929
        # Storage Configuration
        persistence:
          config:
            enabled: true
            type: pvc
            storageClass: "longhorn"
            size: 2Gi
          media:
            enabled: true
            type: pvc
            existingClaim: nfs-media-pvc
            mountPath: /tv
        # Networking
        ingress:
          main:
            enabled: true
            integrations:
              traefik:
                enabled: true
            hosts:
              - host: tv.smeyer.ca
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
