apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.linuxserver.io
    chart: sonarr
    targetRevision: 6.5.3  # This is the current stable version
    helm:
      values: |
        image:
          repository: lscr.io/linuxserver/sonarr
          tag: latest
        env:
          TZ: America/Toronto # Set your timezone
          PUID: 1000
          PGID: 1000
        persistence:
          config:
            enabled: true
            storageClass: "longhorn"
            size: 2Gi
          # This maps to your existing bound PVC
          media:
            enabled: true
            existingClaim: nfs-media-pvc
            mountPath: /tv
        ingress:
          main:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: traefik
            hosts:
              - host: tv.smeyer.ca
                paths:
                  - path: /
                    pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
