apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
  labels:
    app: renovate
spec:
  project: default
  source:
    repoURL: https://github.com/bobo-bc/talos.git
    targetRevision: HEAD
    path: manifests/renovate
  destination:
    server: https://kubernetes.default.svc
    namespace: renovate
  ignoreDifferences:             # ADD THIS BLOCK
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec
        - /metadata
  syncPolicy:
    automated:
      prune: false               # CHANGE from true to false
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
