apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-forward-auth
resources:
  - namespace.yaml
  - ConfigMap.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - Middleware.yaml
generators:
  - ksops-generator.yaml
