#ENC[AES256_GCM,data:cFEtJmPte6b1DtoJNm7iJ6vUT8AUlbrFILLR3Kwvg3RuYTWpYFCuDI5gmt9oeV6H/pm0WJIdoiD7b8PxJ0fH$
#ENC[AES256_GCM,data:eqwplq4oyR1xXVc1iczR5WIoFxOKzAk6YXBMbIW9YVX4ZyR9u+sUzv0=,iv:TSwAlK/cOVYI8oyGZGOlSVvm$
#ENC[AES256_GCM,data:wqIy1cv6HipKU4Exu/++w0qxJbs6LC5gh08A7gl53675HDcvPA==,iv:zUVWNYDKXVnv3rLWLVYaS2L0GZ+c$
#ENC[AES256_GCM,data:Sy+quFOsz3uU8/enMUMlrmGEMhJ9NeUkeyh1MD72TU1q3sGgR5w=,iv:zL9/MzMoc80P14Fnkwyuz1VWe682$
#ENC[AES256_GCM,data:8UEmJoXzK0+Tkfdcupv/TElFakQL9DcLFaSxHUlfRaAw1b1E1xbTmqJ5FqIQUHVVriGCrB1kJjD8gzPXPNnS$
apiVersion: ENC[AES256_GCM,data:qzE=,iv:dbIOC2s4HjxRd03GpUgaIGCzDyTKimCsHuhedIlpQBk=,tag:LzLJ47zd4q8O0kZ2$
kind: ENC[AES256_GCM,data:XZ5zCzUa,iv:+hBLK7q/NK0qXeqilx3X3ViKUh5RgO51LuHrBwcVQjw=,tag:Luj9IdTRR+1Vu0w7sB$
metadata:
    name: ENC[AES256_GCM,data:Eczx1/F/zmVzm2NAeheIbE7a7GSfqmXh488I,iv:/J5x8TCOvboRq1031T/cPnDYGdANuxSYwTH$
    namespace: ENC[AES256_GCM,data:Yob09kqr1utkM0sHaDlxpb1UpWY=,iv:/ozlVy79Oj7iQZDlxomcE5qcZYU7wB9fLhgw4B$
type: ENC[AES256_GCM,data:wDDTFBjQ,iv:wXlMTUQ10MsjZP/fYyRfniu6dT/cDXiHeLYm+yodvjc=,tag:pj/ZeP9rZ/8+yH4bjj$
stringData:
    #ENC[AES256_GCM,data:rZvq07rGL2qfBQ5XGnURsI46Oo3fnOHkGD9YAMeuK4Bf44QY,iv:gTHaIC7l1PxU0XRSsHq0QATjr5lU$
    POCKETID_CLIENT_ID: ENC[AES256_GCM,data:S4MKa70nOfRZTyF8pDAdgOZC346S4ix1jJlSVJRtiWLYzkGv,iv:V9MK2xwbl$
    #ENC[AES256_GCM,data:FbQSSWi5R0VTfh4tH5g3ukKvtaDLGlB/ecUFdYFNEOCy/AyrUwE/Ew==,iv:siXjzoRmV/FpEa2zR8W/$
    #ENC[AES256_GCM,data:MMcbpPHz95WrlfhDgwXk/nn8ZnH2wfI6aM6EiI0gR/PFLj474t3ghLrQ9H4ZLGVgXA==,iv:R0rx9Pe0$
    client-secret: ENC[AES256_GCM,data:SoV9XkM5SiflJGbYwsM+qGkoC2/fDJxW7tYQzkrYt38=,iv:3BAbYwKcYnQoCWGzjT$
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbU5GWUR1NnBhNThWRC9i
            S1hmZnhjV2tITVBQbFEySG52OW5BWGhUK3pzCkl4NDdIczZMcUQwSi9TZk4xK3I1
            UlRGOG9UN2xaQ2QrSm05aUNZbVd5dlkKLS0tIEc4Qm1SRzhCRVhkMzloMGF5dXFm
            SjcxSUx2QUZHeWJhdlhwYkxvYTJMVkEK7JJJrczvqeQi/pc0IV1xoFQmH1MLF7vd
            WzxrVSY363D7SNAakgrtBbzv6gm7mPTGc+weIGlbtulKvZHPU+ZVxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T17:52:13Z"
    mac: ENC[AES256_GCM,data:umtRCy5+O0i7HX3ZI5HpMlzVidXFK+Nul5Z7Bf9DkpQdk4hKldLDts2WDf8mUSvp4Zz997dyWNIC$
    unencrypted_suffix: _unencrypted
    version: 3.12.2
