
apiVersion: ENC[AES256_GCM,data:qzE=,iv:dbIOC2s4HjxRd03GpUgaIGCzDyTKimCsHuhedIlpQBk=,tag:LzLJ47zd4q8O0kZ2$
kind: ENC[AES256_GCM,data:XZ5zCzUa,iv:+hBLK7q/NK0qXeqilx3X3ViKUh5RgO51LuHrBwcVQjw=,tag:Luj9IdTRR+1Vu0w7sB$
metadata:
    name: ENC[AES256_GCM,data:Eczx1/F/zmVzm2NAeheIbE7a7GSfqmXh488I,iv:/J5x8TCOvboRq1031T/cPnDYGdANuxSYwTH$
    namespace: ENC[AES256_GCM,data:Yob09kqr1utkM0sHaDlxpb1UpWY=,iv:/ozlVy79Oj7iQZDlxomcE5qcZYU7wB9fLhgw4B$
type: ENC[AES256_GCM,data:wDDTFBjQ,iv:wXlMTUQ10MsjZP/fYyRfniu6dT/cDXiHeLYm+yodvjc=,tag:pj/ZeP9rZ/8+yH4bjj$
stringData:
    POCKETID_CLIENT_ID: ENC[AES256_GCM,data:S4MKa70nOfRZTyF8pDAdgOZC346S4ix1jJlSVJRtiWLYzkGv,iv:V9MK2xwbl$
    client-secret: ENC[AES256_GCM,data:SoV9XkM5SiflJGbYwsM+qGkoC2/fDJxW7tYQzkrYt38=,iv:3BAbYwKcYnQoCWGzjT$
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbU5GWUR1NnBhNThWRC9i
            S1hmZnhjV2tITVBQbFEySG52OW5BWGhUK3pzCkl4NDdIczZMcUQwSi9TZk4xK3I1
            UlRGOG9UN2xaQ2QrSm05aUNZbVd5dlkKLS0tIEc4Qm1SRzhCRVhkMzloMGF5dXFm
            SjcxSUx2QUZHeWJhdlhwYkxvYTJMVkEK7JJJrczvqeQi/pc0IV1xoFQmH1MLF7vd
            WzxrVSY363D7SNAakgrtBbzv6gm7mPTGc+weIGlbtulKvZHPU+ZVxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T17:52:13Z"
    mac: ENC[AES256_GCM,data:umtRCy5+O0i7HX3ZI5HpMlzVidXFK+Nul5Z7Bf9DkpQdk4hKldLDts2WDf8mUSvp4Zz997dyWNIC$
    unencrypted_suffix: _unencrypted
    version: 3.12.2
