#ENC[AES256_GCM,data:6WB2Wm7xEwuOePBe7H4a+2ovmm7kTmwX/SGuJYKJJ+Uy6oYUc56rm3t6clxqZSqx2SM5bK/CyHwJ0ekppSN8$
#ENC[AES256_GCM,data:mCKPgPKO7cn8Ncc9IIUEvDuAbDGzdsHnvF273uTdd8ZL6woKP4MajYc=,iv:vuICb626O3dIiMPKyjKyK9MT$
#ENC[AES256_GCM,data:1F51jA1cWXQpxqHKLuhkPLBHjycERY8ylmGyghr+xa2HxBoktQ==,iv:cmqnHRTBXxeUojU0FwCtyzfbiVFB$
#ENC[AES256_GCM,data:SImiHSFTPjai27TdfnIzdNGHV7+C12o1bvilefxMd6u8mpSEXl0=,iv:HHiv/9avIxx7M2MAkizutnO5QJ/+$
#ENC[AES256_GCM,data:awiJAUe22CQZdRJRu9DBVQcxtvKc67RybsR2u577aW2aNmLKB/nJfVFLJAA1LSSHr46UmYqOCzxxggiHZco+$
apiVersion: ENC[AES256_GCM,data:88s=,iv:tkbTMM3Xi/W7AVdTF6n+tSZVv0U5RgF5kPx2hzp7tTY=,tag:kJ8iEQpNK7wUH3Vj$
kind: ENC[AES256_GCM,data:fihPlaLw,iv:BZOlhpQmzhJNg37BdF3BsEEUlR91xIwNVUdyBi7ioJA=,tag:VOSBQ8Xr7C/A4Tkdxg$
metadata:
    name: ENC[AES256_GCM,data:pRWwxM9iwoiDZCfcnPnlvvYVBZeCEOfPfGFc,iv:WmszeKIkgIMGyJ840grSAYWacuwPcbbtbFv$
    namespace: ENC[AES256_GCM,data:gf7lBuZu/pTUbwz1NTZIkcmLghc=,iv:Cixagk93isnPpfGu20Y6KUdw9Sth0WdzmnhLI3$
type: ENC[AES256_GCM,data:DowUW16U,iv:os5ieIYhMmL+ZAI938Sqhg2PHh5O7ZbvkuYNX+u/jII=,tag:smKf2OLnhYjxj8aNMt$
stringData:
    #ENC[AES256_GCM,data:HRp3ExVKnaiRY1JqDJ7O5dW6bi0UoD/2lWUKQj38+RjmDQWm,iv:80cWUjTzjjWH7Lk2amdCZiDOkNkV$
    POCKETID_CLIENT_ID: ENC[AES256_GCM,data:a7rey/J4jcTOiJKsJsaGUosZo68SHZ/z5orqYvI9HYf544ah,iv:buWrL2Kgh$
    #ENC[AES256_GCM,data:mK4jE0UbsJ1JMdFiYRvEaZsn2HUA8eMQ4rGfpjXEplu8X4vfHmOSjA==,iv:G+Juw52XsbA7Kt0cSV6c$
    #ENC[AES256_GCM,data:nFHNKd5J1Z+k3EkT5e0IK58LZZvBwizvepKi1zDBWwL2bghKMYtpAgk2cg1UizHEsw==,iv:I2Gi4XHc$
    client-secret: ENC[AES256_GCM,data:NBylFO62d4pnDpxFKtsRikrT0bxL5Lg8mVALlz/s2u0=,iv:IlPBDRdXP+6ENXkK2m$
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOTFTODZuSktTSGlEL3lW
            NmQ5Vm1XbWdsb1JVR29oaVhVVUdBSlFJQUFnCk1WejBLL3BlQStNVlZrWmFxTkxB
            VTl2d3ZHdi91SDhtUlJuOGhUZGVYY2cKLS0tIG4yRllNTTEzb1AwTExtTFNSaXJG
            TFRPTFJIcVJKYldONlZPdk9semo4WDgKBxdI/TFz+IwUxTPI93ACEgKdTeQU0ZJk
            LcqdoqE2IxKMOFangtPIPWkTBBYc1ilr4ng8Mp8N0bnIkGWiH46G6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T18:16:44Z"
    mac: ENC[AES256_GCM,data:Q0ujL5lJQR0Tslo7MBB0f0rctyk2x7G4zvanTOrjtKG4f6EHyDz15vhu8SLJPUXzMk4QMTbDL+RP$
    unencrypted_suffix: _unencrypted
    version: 3.12.2
