apiVersion: ENC[AES256_GCM,data:syg=,iv:fw0s8ZMA6oa6DHwnqcXNZkU9pm3VIG7bCENY5lMnb8I=,tag:PEJ92ilZ/uGXoHt1cEDWvg==,type:str]
kind: ENC[AES256_GCM,data:5n1E+CgL,iv:/pqjULk1/gGXd0ecpQ5Js9usL+OqrJa9z2QoeWBU/iY=,tag:BS3kRXpAVGk8wvwQMaJcjA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:P3cnOpkdNlBcolYzE2dk7teHoiQv1Q==,iv:swOr6hsECFesdjpGFZHoOQxPXxWTPfl2B/qjcSpmNtE=,tag:vIe3ZTUwcq0ug3eh9D6JBg==,type:str]
    namespace: ENC[AES256_GCM,data:d6B96MBeENGPpBY=,iv:HC93RQOHRKaALEfgzLJ8v4s3UQtWP5/lvMwvxYB/XqU=,tag:ztUjsth7dKZsTH+qQUebEA==,type:str]
type: ENC[AES256_GCM,data:Joinxhly,iv:URomy5olESu8O62EbY+IbwkN9Y6VNXufmSZVdsOPkMo=,tag:Fy075scHu6SHET05jbPL4Q==,type:str]
stringData:
    #ENC[AES256_GCM,data:st11fKsmh+aHiA56UvO7rtnX7CFAiWR50CO2fTQGe5Z5zNW9uLbrtQV1NxhU7ju22IKyMCEXyxOtFAkXwxCetuia0q13lj0=,iv:DN8kxa5pLtOLR8Qij1Z1RVSlkCYR/kB6PehmjAW35d0=,tag:LRu6iJsBUAQC8iQTOIb/WA==,type:comment]
    RELAY_MAILGUN_USER: ENC[AES256_GCM,data:f+3/hsO8yaRtdTjmYzoQ9uyEMfIqO7s=,iv:HrCYrQaRKCN3vpm1kULY+9QI/SJ6CS1GIyhNAUj3fNo=,tag:QhLMT5qg4VB0GkGO7a04OA==,type:str]
    RELAY_MAILGUN_PASSWORD: ENC[AES256_GCM,data:DGy/kc1cGnpO02deGIRnfivnVOUYwjAJKxy3euSCl8GDM/mKTKKpuGK29KoHJTwW4zk=,iv:qmhBhC+Z3A+mU5+X9p4vse75IFEEFUeMThPLJM++Bm0=,tag:3SjZCFQwIp7iANvkzbfHkw==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QksrUUhCNW1KOXJoK0xR
            RFlBckw0RDhQemJ3TmdiTDN0cUxjTWl0UjN3CitybEg1RlFNa09sZ1hEOHJSOXg3
            ek40MHNPczVtK3Y0L1M4VjhmbVRaa1EKLS0tIFdBK1RkSzB3dlRlSDY3UnI3RkZL
            cFl1NGVKakczZ3BqMlNoYURFcGt2azgKeYJBevXXAbgf3shHWoESGwhB/ut/m5cp
            7KkLrXIdOTZPGOsWrJnfL+NGoTMI3Nq5DI3iqfgnjYzw1SCXZX9kAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T21:57:52Z"
    mac: ENC[AES256_GCM,data:57EilaTOJVQc0p1Y14cQsCMC8+WfZJr1OmVH+TWCjqU+J7U9E4c8y1w8ZAwdgD/ggG9FOh0QkeEJX74R4MLSxqDkx1vZsRtmqiaQGIAYN5hQI5gE/aQQJ2LsAnSnrr7749TPQkTo1sMLkGX8RgS4PjHllKpEbZCNVauXT5FvunA=,iv:JaULF1x/+zCJ178b4ZzYhlgzQjTNToBvijxyFOLUi48=,tag:xJSTm67+AY4drnKV+2OI8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
