apiVersion: ENC[AES256_GCM,data:fe0=,iv:wzOpAKF5GS1ixEdnjuUDQxN1YjvkVGlDNnCtDWOGHgc=,tag:JY14EaPx1wgrqP78ZsF4cA==,type:str]
kind: ENC[AES256_GCM,data:dDkIfnnA,iv:vO9BZm7LhHZGQ1HMrQRvidwznyFo3KTO88nz9GbareE=,tag:P5d7EAXM5LihA7DbleQWxQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:s9o1OipdYsoF7sLlIQ8cun4B2VcpKQ==,iv:ZpNosmWuWHN0EsjqAPXY/Aet7EO7hyj1vJUn90TAnAg=,tag:+ogucyWod7TZk2C/NiciPQ==,type:str]
    namespace: ENC[AES256_GCM,data:s4Ks801hXgvzwvE=,iv:VR8uyh1tIqNDVKCtpdHW6djdUBMzC96LLTpeAIkqn3U=,tag:L/Tw5y7sQR4e6UkxOXncRA==,type:str]
type: ENC[AES256_GCM,data:4l5R8kie,iv:BWfAS/SQvNe6g83nTvkOto0JF7IARKOK69D5wKg+/8I=,tag:Pd8BqVnIHSWoudt4eAuzmg==,type:str]
stringData:
    #ENC[AES256_GCM,data:qbMk50+EZCbnt8G/azzB7eKzFTHN7wNW6AQqVQyNOZ+dNr0uXGc3UA3t+BLMgtKnN9Q+PUFm00cT3kHayL4CMFXqLf2pOE8=,iv:Z8bLf9jP2Rr5tBHOTeJG+Hp2ALheFGfAOoYqemdALvM=,tag:s+GcdpgdDfg81z7mE0CzTQ==,type:comment]
    RELAY_MAILGUN_ADDRESS: ENC[AES256_GCM,data:6aXGgAkj/pjMljH97pwod5VWvS8=,iv:KiMKr3C1IOJGlz2o550DJAsWkWfbk/EAHJnNbUoymig=,tag:02DQUo1g31OD5Y0ZVLSaKw==,type:str]
    RELAY_MAILGUN_PASSWORD: ENC[AES256_GCM,data:ZCPAEAiZvSdqxA0eM2GgvTvHpjxLY4qH1jB0zru5avczIo0txC8j1BYOW6nnYRQbIv8=,iv:ANqbe1RZTZMt3P0/XqTb0b+bA2JR8jX7DEalat6Xntk=,tag:lY1a1gZWnh8TL6cPqgs2Mw==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYTlZOVNKelV1UE5iZzgr
            eUJNREUvSkJrWWJ3b1haTTV0a1dKRFZ5VUhJCjNkdUh4VDRjTVpwRWswK050SFQr
            bWdHOFJCeUdLTUt3elY4QmFBTHBWd00KLS0tIExBakFoYW9FOXoyV2lBcGlwM2RN
            YlZjUnZlaE41RXdLNmY4bkJWbzg5NGMKizhqTtC1eYQYKj/+ZzOrlF92zmFPNXHi
            nBLrwtB5YmAk0tt1UeNGyYMiOIJcJ7OINBScNtzuJabDNBVSKeY4jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T15:54:02Z"
    mac: ENC[AES256_GCM,data:ciGc4B1j946YogrzlAoWtxcM31Fwtoo3mFed3bNWjys+sI7n+Njlr0Pm692crymfrkq0X0W3n4XbRpUrMvRGvNoc21UtnDq4vmHn4UZ2BBMNxzzt4D6baSQvNYfFoOaM4A+WXS6iF0FPtAsQMfKIzoV7z+s1mixG48IKZ4zvXio=,iv:rzc01E9U6V4tfkHSiGd1R4OJabU3cNSm7y0Gu4vcGHg=,tag:uFYqhN51akrCJ7MQkhtz0w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
