---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex-ingress
  namespace: media
spec:
  entryPoints:
    - web        # Port 80
    - websecure  # Port 443
  routes:
  - match: Host(`plex.smeyer.ca`)
    kind: Rule
    services:
    - name: plex-backend
      port: 32400
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: plex-backend
  namespace: media
spec:
  # This is the "Magic" - it tells Traefik to go straight to the IP 
  # and skip all Kubernetes endpoint/pod discovery.
  externalName: 10.0.2.10
