---
apiVersion: v1
kind: Service
metadata:
  name: external-plex
  namespace: media
spec:
  # This tells Kubernetes to route traffic for this service to your external IP
  externalIPs:
    - 10.0.2.10 # <--- Your Plex IP
  ports:
    - name: web
      protocol: TCP
      port: 32400
      targetPort: 32400
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: media
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: plex.smeyer.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-plex
            port:
              number: 32400
