apiVersion: ENC[AES256_GCM,data:4TU=,iv:x4lF0FM/Yxk8d5faRbpXfUtD172mVIEScc2vIS75/vU=,tag:mEAHAo1oAE66uH4x91kAmA==,type:str]
data:
    api-token: ENC[AES256_GCM,data:HROyC9/GxXqZXb8eEhopdU9P7hQNnwlzM5s3S/o6M3oDCzNuWAy/MtRJCrwLu7ccTGgfUCfiWpQ=,iv:0n0SfRUuO1oE9nC7PLGYInSBtgFwc5prUOj/vxmDlRM=,tag:X1PFdfi6Uoc7RHZZIF9j+w==,type:str]
kind: ENC[AES256_GCM,data:lfG0bzdj,iv:cZD1Oqsm3lSdJw4i03tCqPzIWtrErtrtCd0A9wW2jxg=,tag:zu37iZqBN4uaepxnkqs2ZA==,type:str]
metadata:
    annotations:
        kubectl.kubernetes.io/last-applied-configuration: ENC[AES256_GCM,data:LI8e2FC84eovH/YyDYJKyrdwYGUM3dd5VPEwaUVxgUwuJ8dAmCJofmn4OphKdMMv8QQgf4AVPXXuBuAVG7UcOCQRrn0RjRWDsH9a+1Ag8mtTN5p6bor9nMRmjgYW3qXMewdYFzIeLWBRio7Rqg0UGHa/3m5rkjyfoa3KFHPgb+YTb9w7orVZLlZaVdjFqMSLVRfJcYXyKvsr2PwtsDjYxiclkRFyVpiK3pwFVZXC6DYn3Gc7R+rO/aVaHkAIOcERM9UMTUY1oFdmeqZxXjYvjQEy,iv:bRuPvPBUurJ3qw3OhaKxmDTixcTkgLLtPlfEXUxMG5k=,tag:46gkWeA3YnVIks7qpn2edg==,type:str]
    name: ENC[AES256_GCM,data:GTLFiFV98IpcMK/bmL8l6HwyfYAkXLOPrEh4,iv:TDmz39BfKgqlqx67Z2zZ3KJq1KZ2K/5jtT8wSF59vn0=,tag:Y39kvx2GiGxmYo5BSEo3Gg==,type:str]
    namespace: ENC[AES256_GCM,data:hiwnm5qwp+U/IFyf,iv:EhqIFQu4qNKNkv8P06OziILm039TUrllihj0v1+zHpo=,tag:aDvMuBQc9P/dsffQCS8HgA==,type:str]
type: ENC[AES256_GCM,data:tYs4CAnL,iv:+AeZ+gpzBaUGEW85YulMT4KUEG67OR5oFqUt0pPyIn4=,tag:4YvewhXeqmdmosjhBzR80A==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3d0R0SXQreGJSS2t6UnNX
            TStwTnd3VHUvMFNmdXQwWWRpcU5NOHIxNlQwCklDNUErNExGMjdTZ0ZxSzZzbjhP
            V2QwakhGbTUrTHVxWEFlZVU4U0g2WHcKLS0tIGZ5eDZiOWQ4RTlNcWQySUN2TWN4
            Nno1cnJMeENScWwzem4zQ2g1eHhsUFUKFJ8/nyJpnUwVWKUrqI+3X1RmiDNR5mQ2
            ioiwdMyM+Ij6a9fxBnMqJrF9xEB1eL0//sfsQCK0VzKq0ocmdp1jEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T19:38:42Z"
    mac: ENC[AES256_GCM,data:biiha+TfNL3RNKBFc9Ar+3NDVl30cpzTibf3/Rv3Q6g4BGU8MLOu9ei3o4z9F2oVFHgspPY0qmtuCIanU8uHejisHHQMgrjPbS84Fmx+s3mS+BncjPsYUXpCxmvWUrZ8dDSUfaR8PUGHDGy8F6xUg19d4mRqLB/t3RB96h4XFgQ=,iv:rL1Q/c/2uEZMqQwL123SHQFZQoWJW3uinSsyUowQsYU=,tag:pMbqzIFdSO2KTnupnsUSoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
