apiVersion: v1
kind: ConfigMap
metadata:
  name: wikijs-config
  namespace: wikijs
data:
  config.yml: |
    bindIP: 0.0.0.0
    port: 3000
    db:
      type: postgres
      host: wikijs-postgresql
      port: 5432
      user: wikijs
      pass: $(DB_PASS)
      db: wikijs
      ssl: false
    logLevel: info
