apiVersion: ENC[AES256_GCM,data:Pb8=,iv:D1+3pdkEPanL0pKtdpRllwoPHuNIrGgrnnTRSbETh4E=,tag:4DOsLPvaYNDT7J/ZV1UBew==,type:str]
data:
    password: ENC[AES256_GCM,data:wDhp0HH0jQ53dn6u,iv:4lEQ4UmoWeKQZ3T+X460Bm2CIuppHCxlZnfZgA8ccKY=,tag:FdFLDK4MQ9ER7yIOEI9+lg==,type:str]
    postgres-password: ENC[AES256_GCM,data:wzzBgM1EwEuenhD7,iv:bcFRWmj+OeWyJzMjRdVH4l84UqRTavpa3ywJY7pJ+1g=,tag:WlRvCjf6JE0Cy9uvnlB1Pg==,type:str]
    postgresql-username: ENC[AES256_GCM,data:dkGDuSuGi49l3YML,iv:tZBL+ZlrhwVH7O6sMtjPcfwBBvcU7Guk7z1Pzp9eCQU=,tag:tvZmgLEX8Rxi/LqC6TXBOg==,type:str]
kind: ENC[AES256_GCM,data:vHwI5ZGv,iv:lemgKaZVxLj3PiPlJ+SXE+Rw03qW9JzH/ziXKUXv+ZE=,tag:Z1eNsvb6BROusm9ojZB6kQ==,type:str]
metadata:
    labels:
        io.portainer.kubernetes.configuration.owner: ENC[AES256_GCM,data:AQeT4iw=,iv:TwPicwh5cbW4cg81g38sHHtLVPDjteIVZNrbJg4Q1Vk=,tag:j60pB1DPuDai74V/vtPC1g==,type:str]
    name: ENC[AES256_GCM,data:gFJSi2PuvonzTPv81Lc=,iv:F0AcJc+4o6ZzdUc1rXVXB3usqJcAkKwfjNFYkuhkzn0=,tag:naTMxe3XeUKUoxiG+21AAg==,type:str]
    namespace: ENC[AES256_GCM,data:mvVGe2Mr,iv:Z0O/am0sWHJyqjC0NAnkTrgsJAp8Irvjg9LG27HILMI=,tag:XMH4BraW8NBZjThBuJB1bA==,type:str]
type: ENC[AES256_GCM,data:CS8D0mZQ,iv:pfrwMPhfSSF4yODIL7X4V1LB0leNK6mcdc6ci4Ml7pk=,tag:x85GeGCWLGLMJoZIzn0gEw==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJU2NDeFFsQWd6WFhDUGw2
            WDdNZDNpNzBzOXk3YUYrbUE3dUJkMy9ubGhZCkd1RkRBU2pNNVUyL3JPRW9nYmpu
            TVV3cWNCdlNlQ1NsV2hEVXVyTVdJeFEKLS0tIEViRlg2MGFUdmswbVZXOHJYaGkr
            NDVPVVZSeEdUZ3hwNUkzZjFPa3V3WWsKrQ+AGCWPzUkm9lmRKb6ZWCCAzYhrd7H5
            sOQeEZ0w25LY32BiHDyb/ShZcZOnRccwQkseRPAIBcl9WYFhPYDwdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T19:40:24Z"
    mac: ENC[AES256_GCM,data:PdB1/pBMwOzaylXVOfEeC1MCKZMfwp8rPSMAryO0urLc7X2uT8fSEDmIlJJqD8OgMvl1w3uT1pw9s15pE9M7gT+nHIDVYlefVD7F3IzuNK7U+IIOkL84HpP3bT8I5kGGzux8yEzAyt8jRvGLkpVNaylZuQZ58AfHaJZXWLWTFsU=,iv:kZhJJB8X/t3RDrVaaNIydM0YElyhD6mGO502pLjRcLU=,tag:cABOoN63LNyg9fs19wT+TA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
