apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kavita-redirect-https
  namespace: media
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kavita
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`read.smeyer.ca`)
      kind: Rule
   #   middlewares:
   #     - name: pocketid-auth
   #       namespace: traefik-forward-auth
      services:
        - name: kavita
          port: 80
  tls:
    secretName: wildcard-smeyer-ca-tls 
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kavita-http
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`read.smeyer.ca`)
      kind: Rule
      middlewares:
        - name: kavita-redirect-https
      services:
        - name: kavita
          port: 80
