#ENC[AES256_GCM,data:CnY680z13zaSA9q1DeSlFTazHqoFjteCEYqsC7ewxlc12KSr5zGPv/N0H8S2jyugbfVwHJKsU5iaRXUZplvAxQYSJqu3POXMbvJNneY2,iv:nkkFmrfi0uxlJ9LakTO5/HTEXNsr+2D4tSn/RiMtG0o=,tag:oVuOjNVCrgYaIIBpAjf86A==,type:comment]
#ENC[AES256_GCM,data:yP1Fe77pAf4nBmRCbsij+19vaq08QZpGr6sS6RFn,iv:e7c6NLyn/cpY55p4/c8HFur+GSEpLeEGH6uOca5zAjc=,tag:CvvgLQQlhw90Po1BToEgTA==,type:comment]
#ENC[AES256_GCM,data:wPRXIZROS73HiHAwJsk+eTgElfeYoGyTobO61Mu3BbPn+8vAQdJmXWkePM8=,iv:5qb+upmYA5gtJnv9SkqPNUBZI0b7fqnqY1DQiyGdn7Q=,tag:/fhyEpXwAYnY5VZavyY/mg==,type:comment]
#ENC[AES256_GCM,data:+vY+LZzI0AM3GOSwH+wql7ee2bq3nGyBKZE8g+pe1FAlk2qHAhoI7r5iQstyXlfaVYQx9JrNUz5RYfKPF2FEkcnHxgsfWKFHbhl1,iv:0IZohZOYUx3s7p3v1F+9OPNm/j4JFxtZuYnvJMIuFpQ=,tag:0J4dSxldtNOVY6kQotj6gA==,type:comment]
#ENC[AES256_GCM,data:LzLkbEJQvWKDWbP4OUQKuWmnjEvHNOq2CMYwhuDoWGhqN2Hd80RNzVqDzOBnPO2dVqc1OO3k92+gqL58HBh3104J+0iCpVmU2gYawppo,iv:11UfCY/nGnKl8PvUV1n28QH4zrCEpro52R/XwDibVSc=,tag:rzbkYfnrgHAZKO9+1BOo+A==,type:comment]
apiVersion: ENC[AES256_GCM,data:5h8=,iv:ekxqzZKf+1lVLVfFsvyKtLUu42E5csp/z6OOZZMugnI=,tag:QGt0wxnfxDtlHseeaA5clw==,type:str]
kind: ENC[AES256_GCM,data:lGcgd/GK,iv:ndK/iTdwJE/M5OE+VxTOk30yU6/x4ICkqbmvTf7NYLk=,tag:R6KWfCH8SUhfj1U3uHRFwg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:S3yRbXMfsbHaPMgSAYtM2sU=,iv:LOTnKNPrEGvC0YAPdg/CLKQYd3WBYUyFU9Zu6RRb1qY=,tag:bsMeYY0ee7bzdta1Hcie6A==,type:str]
    namespace: ENC[AES256_GCM,data:DWurVU/Gl8Ys,iv:kwMrmGs+MiIMZ0fYH2bAtNLAKLkT7pk/E8ubI/iTtac=,tag:eDTAV/tRxmtCldqTHysTdg==,type:str]
type: ENC[AES256_GCM,data:iNcfckii,iv:W/u1im1renWwvWg/+l9iTr4pPSdCeezSNb78bnHA+Is=,tag:2xJ5rQJH24T+o1De4VIXOw==,type:str]
stringData:
    #ENC[AES256_GCM,data:5IcCtX6wvvK7tTMLnmmIo3Y65am0fK7NbPyrCWgkqZLRSNyO/A==,iv:EuGRRAt0rMz7MCEc6+DChatZV0J1nFPX3khUQEjMLqg=,tag:81mMuIMQVKq28qW2C5nw6w==,type:comment]
    #ENC[AES256_GCM,data:/PXnlrZ420efxVZtnFyTVGAkUU+2LCsv,iv:0RoEOJx3L4+W/CKvqrPYAl6RNBIT8ubLfHyzhFB+TMY=,tag:2KxPYvx2EpveocswvlLkKg==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:NVCDkUzfGhBxNfuT1yKHAModlS0RU+ZISbLBdB9tnpBqJguA8ISVGhnt2mCJi8tZWqR18v0pXsz8LH9mWPmjBLFR89PY,iv:mh9VbnuqQU8DtQjceYzJ4E+NlG+yoxdvWp7zORLvT/o=,tag:GMdPk+DVPEO5ppFQN8T9WQ==,type:str]
    #ENC[AES256_GCM,data:IA4v0Kki/+xgG92KdsiY748rnaM=,iv:Eq9uOW+hY8+FZmbYpilV91iHgD3KDy22N64Pnkiy5O4=,tag:KPDtRRW9qhzFnHFzLi0k7Q==,type:comment]
    AUTHENTIK_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:qMg+UNIbfkqwr4k2zA/dxDQsLeviafA2WOklh4vozxYOuaQherXyuG1GCmQ=,iv:MntA/X3nsasuEIunEqBipq7oVj8CFCwWgO1T9ZYSYFs=,tag:KWhCNrwW5lj9XbXjtlgLrw==,type:str]
    #ENC[AES256_GCM,data:PlNNr2EHN+H//0zq0wv0,iv:O/8Uj6MkzL+96AA4Oyk5sutlyZJ51CAOkS5D4Vmdu8M=,tag:io1K4dQjA4bNPl4TckqHRg==,type:comment]
    AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:oqnXSTvKcZ4gO4DWZAL/W2piFEoiso8w35fWufC5HWuShPGX5hufMTdksJg=,iv:Cx2b1D4IiIfm6PdfUXsgaqCvDELbxobDgjHkvDS1pyc=,tag:Xmfn376bXqmC7nVzKjrNBw==,type:str]
    #ENC[AES256_GCM,data:ZPbCTxj1zNtBwvUEd0XfBNx/yf3XrA==,iv:f1CJIdEcWAv3aJx6UPsuOqhfMPeeUK7HLLA9Dfyjodk=,tag:h7QVa55ABh8u7xUvsAqwCQ==,type:comment]
    AUTHENTIK_EMAIL_PASSWORD: ENC[AES256_GCM,data:gd3HaZCznHwCDLa8u13SSm2UazHG4+qsjZ65Gsl7Vvqrk6tFFj5ViSiYb6nRW0D1IT0=,iv:25AFs6IF84RB1hEMPnyY/OPcS40VjwTn9QsackoBy1o=,tag:rdQ78TsrOBehM5R5oaLQlw==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeVBPdDVTaUt3TnJIZEMx
            UmljRFJrbDZUMmJNaHpjVWhmZDNVYmNVcFQwClF4TDZvSWM2RHhuN29WTVdmZGNY
            clpxYW1iM1F3aDBQUDMvV0dtRDErRzAKLS0tIEo4L3J1ZjFqMDVYbnFMakhEbkpG
            bHQ3Yzl1emNKa3dscmtCU3lpa01hdzAKRCSPKFd4XIHwe3841L+KYjrf+gkE5H42
            4GxllZuEK8qhVj3HkpkzBMujzZVa1ZhGLGM4c9lL9TE5B2Mg8s9tOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T23:21:37Z"
    mac: ENC[AES256_GCM,data:/gCjVjrVAWAsS9D9oGzMulTBgR3NDEakSBX0VFjOY0KrWEvcexP8+mO9UK+om7CSXHamZj2UEsjd5DRIbIn8pTBwEUxqYpHxCI81SLMDl+45TpfY1KQWAWdRm58VP9NZ0hShMJ4YLYVzOAIGl32HW1OaqTrTjR2ILUEFFi7LLXw=,iv:JYNLXF3sWa6Ya/LccVgeSsXxRWt8pFyWxzNTXkzRj8k=,tag:ETvP7tLmIpVkHp8ab3YNbA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
