#ENC[AES256_GCM,data:CEoMmj89yng8TpjtEVWASqURgAtEF773x+CLuvik6+rFLwmql9jUqNGKYgrnqVP6NHqYjNbmqwXpiTbWV6DBHePPj6T7skGS8ZBEBrHQ,iv:5gygP39xpzqZql6Ry7uw6MyRhQYGD7ICQGb7TJDvnE8=,tag:lvbOrTK7wOwx/8MnT0ZSFQ==,type:comment]
#ENC[AES256_GCM,data:X/BlncGCfYH2VubOvB6GS6rc4k0U31lMO77I8jcM,iv:7gMnYndrhytpjMNbqTCpLLnBcGtLJE8Yq9W9g8anLE8=,tag:nu+w9ygSNnoaU0Vx7ncLKg==,type:comment]
#ENC[AES256_GCM,data:poIUcOWCcn8yD5pfvdZE8eJvk4bcTT0jPXFmkV34G9mo7pDy3rQDZou6dz4=,iv:cMSOKfClvX5Fh4ioMQxzjPGXqoYsGjFzzcLsG2qxMFs=,tag:98ULhzGvmbzAOEJPmDnEtA==,type:comment]
#ENC[AES256_GCM,data:2nba78E6DeX7djxmFAM5jgAZJgPdLFChFsFml44wbpaVZjE1LxsnMWqZDhfDbZPn8HgxL104XGZtrTUQJo+uO8w3NCp7+9nGqX9+,iv:Jj1AvQurA+E2Rwk8y9QID1MVPoBTGD6EvWI8VoQe1aw=,tag:NwIFQYz0gXO4VzcL6cB0VQ==,type:comment]
#ENC[AES256_GCM,data:gLt5+Y340mcP3tAWyI0ZAPoN4hDZdwlPAurVvnvPXPDuj2QqtyKBL4OoWhZ6XZWfz9JSMw976/l0A5usfwP+qvK1KuFmC7Vy3ylHHO9H,iv:mVzUVxYmVlOF1hm0dvJtQC6XwCpaWgITTnJF8Qwx+rg=,tag:sZbYQ4PgzuOEX29u4TWFVg==,type:comment]
apiVersion: ENC[AES256_GCM,data:D0I=,iv:N82Ql9pDLC63Ivm8wE41U4pOVd4x4M+L5DTS+a7T2CY=,tag:WOTPSHLqIO2iWCDjQ/0H5w==,type:str]
kind: ENC[AES256_GCM,data:b3xAKxhS,iv:fZlHOrigbIp6EUJLRbJUAuL37tV1t2Jw/QNVAplEpEg=,tag:4rHKiqB663sYcUA61bw2Xg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7FppQKBZ82ASitu3r1hGRso=,iv:nDJDNejCXQbkY1QsT8MUE+J0IXPC3CpqHpQefYM1L2c=,tag:SCUp5ucmfDL7t7Cvcmlhpg==,type:str]
    namespace: ENC[AES256_GCM,data:byPrPCrk4C+B,iv:0ayDX1WA9FDoWAKJylBSZ+VSn2RgUgLSo9qAOTNpuBc=,tag:buwoexQjIa/4ctWwXPg5yQ==,type:str]
type: ENC[AES256_GCM,data:3Rt68DVl,iv:Ih9d+K10+x9XLc65y4Wa/CxqSbPdPnJvqNrlZQ4A67U=,tag:m385cJbab9J0+z+h8JKhHA==,type:str]
stringData:
    #ENC[AES256_GCM,data:jwmHFIB6HMOYXaARF29MnPvMlAuzJT2G1Rbh9vDYAky8zeqC0A==,iv:2HnzJE0BbWNbHETxvTqgQ5L95NJCF0eiOOfBkB+w2no=,tag:cepWJS5o+y4PqQogMr+uLQ==,type:comment]
    #ENC[AES256_GCM,data:rQYN3uj6dmSPMqzltjtFKe7A1lrfZPil,iv:OvzTXjVO0xgGvQOkrl3MVwE/B6vYpOVs4yr6W0FV0uk=,tag:IK0ZG5aptYTPUjhLulyN+Q==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:/mfwHZN4jv/ms84enidRkDxt1rwWgs5UFWMW40mE4MR1YTTh1yX2tysFrrDK7G/7OGSUR7wsUGv4HG3nPxWUhXgT5C8=,iv:zKhxbbQmmNHN7WGvAEQuMU1xfi8gEY2mgNYaBALDSXo=,tag:0ztx9Y32e8Qwobtn3fPWwg==,type:str]
    #ENC[AES256_GCM,data:Su4fICDxXz0RlXPSuoSawMboOPk=,iv:goHLv1RV2JYzskvk9yr7PCfvIDwPonLjNIPi47T+bAU=,tag:CwPYMuM97YX1d02LgswNZA==,type:comment]
    AUTHENTIK_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:OFC/F11aov7l9VpeqAZyZHg1CcPQ4Zsene552S57u79L92P8yebTHBE7hzk=,iv:ojoMsIErrr9wZ9ATIyIQ3ZHUopgTUrRhH9Y+vg8AaIg=,tag:vjFW9hT2l1LVrWKktMq4Wg==,type:str]
    #ENC[AES256_GCM,data:CgqiXcoMzm0IKjmFLgi6,iv:l6W7jm9V41JGp2jfKDlesvn/F8D7weHhFSP8aoEwi+k=,tag:zk9BiB5b+JFPpHK5R/PC4w==,type:comment]
    AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:ElZL9CLg4eH5OxvXHMd0GwFG2ErvrwJw3/g30Myhld1eb+s7vy5Ctzkq2j4=,iv:z0xkH/qM8l30CBBMRrq3dgWnD5EF85xkH9O9giguAgw=,tag:c8iUBCd1lz54ZU/BTq5wfA==,type:str]
    #ENC[AES256_GCM,data:vSk61yCX8WAjk8KvqAPVhRe/l1bqCg==,iv:jvU7ESRX7gzVttY/o2F+HH44C3pwnHsQLE36TWd3rV8=,tag:ww6fIwLXhsFx/l8DiSAb/A==,type:comment]
    AUTHENTIK_EMAIL_PASSWORD: ENC[AES256_GCM,data:VW9lY/4cNDM8svpgcoW/2cGBMdheFqPN/UbTYePyoebKIJmu4Lz6RyuELiu14xmSSgQ=,iv:KcCPUzeo7tm0f4jXOuevO81oOpB7J0x71UgJ06eSG4c=,tag:NtAan71pPHO/TjLKfMSJhg==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRVVJa284bnYyMFBaZkdT
            VXFRZUU0TTNKdXo0VzU4dUFLUG5YYkJjaXpzCkszR04wUWl5L2x3YkR2TFlsbHpm
            U2NEb2kxVVJPMEwvVEZuakxnRjBsQVEKLS0tIGpVRmFXa0VGZ2V4TTNBU1VGRXl4
            aFUzZW9ud05KYVFhQXlxaXZ2UUlubzAKH1FBavCrrXbBN/ICX/dajt0U1599surQ
            VMIpn+a8CMLNjft1VnXyWsK2No+mOv06qt59MTp5syP1g/EEf8zi3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T04:02:45Z"
    mac: ENC[AES256_GCM,data:LOVTACuMbAYT1gAL83VbgOzKRMIgRAMBQNzmUmiXH8Nzg418ozlGlQPfsoLBulHYgXMn1qkM16z9F2JlwbJZeTJm15BQOIAb+kIDYzd84qS1jky2uiTFrQ6iZ5zuyBp/vtYsU7rf1MVx1vEHJv34lwdIdN8uxRNEluI4o8rZ+lE=,iv:pwuyFe2wNwFxFbsJj1vNOtgP10IoeHAql7aJ4OUVJvk=,tag:EVWOiSu+lxou0PPQ8BoqIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
steven@Ma
