apiVersion: ENC[AES256_GCM,data:ajQ=,iv:ohSlhTZMprLH1/LmYzUZvBDIp4bSGjOrrFoQbgx767U=,tag:D3rWAd6HelGuTD4GNhT8tQ==,type:str]
data:
    RADARR_API_KEY: ENC[AES256_GCM,data:iXMDKjApUTNMekNEJ6UcbGgFETt2eiqCdDHnHA3WZ5HUy7J9hmyPteBk3z0=,iv:uQxVjZjmOVC3TrvL85rnfGSSngKNBHolcPnCuSqkBiY=,tag:FQKtXuQmu8UADzs0RiIOwA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:8+yi8kGlCyu00AuZ+d7sFjd9UEp52z5MN9Is3oD5gdN9mvcxnZKHBUHwO48=,iv:2ix29MCdtPxXN3IDryB8fKcKK8DfSRxlcb3J6quL6P4=,tag:GCLtLbTnJMrkQEJ9qXydCQ==,type:str]
kind: ENC[AES256_GCM,data:oMEGS5PL,iv:Exaj6bwE69ZeTiW5gComg/vP2vKlG56a7gWbHzTUa0s=,tag:vBdaGlLVWDh9Xezwd/r3uA==,type:str]
metadata:
    annotations:
        kubectl.kubernetes.io/last-applied-configuration: ENC[AES256_GCM,data:wYvTk6yccuY0CtyRKz8LGokKLVqik/qrgV19Ywq6p9XPvi/sL8wZ0H+fm6+lavJCdUJaKKT4t2VKWHarGlLxxKROcleZcPZXyqla5Eln9h3q1GMJFJ1e4nbKbY8PhWJUviRVK4w6YKqKW4nl/szNL+qsldWMGobQaYK3C4O158cJdMCQafpZHiLuxQP7ryrSW0rqRCcUcAr4zlstkn185VvBfSBEzj/aWPco9Hj7wMKlGfuVaV+AzZ3l4V3Z1qbR4clYEqHghb/xp6QuKUgPcN/CUrCgGtjO3C1F8FfWAJLRoAOp1/NjdnQX7U3SnGE2YxELmjne+PBRp0hJMg==,iv:xoc6MbSO8jdQ1wHkqirzPDro5Wj/VOknRkVlyQfPaSE=,tag:XcuiNu5d/udXQsvin/UdOQ==,type:str]
    name: ENC[AES256_GCM,data:OlQJesJNmz5aUMlNsu0sNK6V,iv:LiFiqYGMysHF/IKnm5BMdlc2/0ihZpKjNP0w8cViKR8=,tag:s7ppLvsBp+WeJ7KB37T1tA==,type:str]
    namespace: ENC[AES256_GCM,data:Wfv3/WOiv/3R,iv:vvQSmrtkxDiHBnPHg08Bb1fDxEaCphFGAaPZ7mrSJRA=,tag:2UFIWxcGLmhK/lDoHPr3IA==,type:str]
type: ENC[AES256_GCM,data:QsdYx8A0,iv:/wu/A0/L91dxs2OR5xzYSPt5Qvz3Cp7JUqxw+YhEJHg=,tag:/QslBh5tSo/qiFWWAwUTCQ==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNVBZNGFDU09YU29ESDV0
            bjJuVCtPaDBnRTJpU01VaUx3S2RwblFNMHc0ClFvN0lMa2xqTnpQMWlvMmNjWW01
            WStsT2tmTnNZVjN0bExPM2wwaFUxVE0KLS0tIExrenNqNGRkWFlLZDljb1U3MmZo
            ek5KWDJCWTI3T1JWWk9IelUxTUZFUU0KKqIT2zfW54jgPPLAsX8wXCKXkGHMWl7d
            YZG6NZbYBdJxiigwTQRxXLnLQWabvnB7qF3dE4iLUm+kpk0rRtRb7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T19:39:54Z"
    mac: ENC[AES256_GCM,data:9ldMQOrgwClVoS6L3m7E87jAWXeelgeVT/QxxfsL0VJXe3QpgezAAfKz4BPCvSpdgNY7FRSbTgPwmz+PeLmDGlR+E7OsBKf8Hq1QqowaRnIHCGRSvnnIo3kUqK5fB6IZhObTWy8RuGldwlYkyCtuCkxx58nvq974keyE8SzbHnM=,iv:b3IpdDGJITdlo7oT5lIp6bTj6/QfP5+w5dbNaEzdG/0=,tag:y+NBzFK9Hw6g8CLFFBEaNg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
