apiVersion: ENC[AES256_GCM,data:qRw=,iv:l4cxwVg8dNz1vLrImZLA95KzcrH6DYBM/ZPs1W4bo0E=,tag:sj9eHbZu7vsPJM83QFO20A==,type:str]
data:
    password: ENC[AES256_GCM,data:1P7bjCEwxU3lluuSDXMa3OAq1srNhBgotH/DZlHxGdk=,iv:W8gC/5XKQ81aYLUbEJ/h4Wr2M9r1f2SRb/CeOavkhJM=,tag:P+1gXcyr+11ZvRzEniqp5g==,type:str]
    username: ENC[AES256_GCM,data:ZrsZxBUa8xErrLx8wgeUPirNR3hd8T/PcaGcKg8YQuM=,iv:8ktGS9h8QhHnzkq0pHhPQ7GtYr0UlhtyKaPduFzyKdo=,tag:N97whBKshPd49AJOo2EsAQ==,type:str]
kind: ENC[AES256_GCM,data:zvb8NwdX,iv:s/KgX85SZ6oxz0312DECa5ciqX50aC+YZpu79DXwkRs=,tag:7w5ljcZa2PFdcvAY/Zqtuw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TBX4ope/bXI=,iv:zzA7wvd0ueArA32zI+AjKFBOFiLLv6KTAnLx9YKOS4M=,tag:RDn8hrZM+UbL6zQOkj2Z+g==,type:str]
    namespace: ENC[AES256_GCM,data:Rg7DpUE=,iv:igwpVC0wn+rAMc3MWSM6m0YKhZntwCmk9e1NuCDV00U=,tag:yM6k6Jv7nWl+mdPKQSsFrA==,type:str]
type: ENC[AES256_GCM,data:WtG5CoKn,iv:8BpgasuuXoPmnJ7BhfqzVxMl0MDelrQNnvoXGt1PqN0=,tag:7/T/N5MlfeiXZkkg8mS0cQ==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDQ3Yy8yZnQrcEh6N1ZH
            d3FhOWIyMkNFV2pFdktXMnF4ekFmVmVOWlhnCkp3cUdpakZEczQ5cjBxeWJmUDUy
            NzVxVDZnbTJIRkk5Y0xvaHdQYVF6bkkKLS0tIHhmNzFmNjZFaSthSXZuaUd5VHFt
            UWJiYUhCTjlwelo1L1U5WXVaUzRLWlEKVWMPm49aBoNNLKc6HwKB2jHm/YtqSImb
            CBXuo/O6cACnHuRm71uYZNVXzCNBfU7xplBO1he9ziVkBgtU1ZvyqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T19:39:21Z"
    mac: ENC[AES256_GCM,data:eZSAg7Ej2+rRySOMzDK1XXrDNcPG49Zb3RsWCv+jFpDtKcBIEF0XYjTdP3B/B9quW6JGdAhFJhN8SmYRdeloQ/mJct4T8K6XY+1aMcZRpQmaMxeG197csv2kHRpD1pVccBKoCbctBsnfc1FxQko3J3WGfz2qAshKAvvUjsByZXA=,iv:6CER/ttv64ov+dKQDklftdpGsZn8hd3jCYpc7ruD0SE=,tag:+AJU3P9CndhVirCZTNZ8TQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
