apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  kubernetes.yaml: |
    mode: cluster

  docker.yaml: ""

  proxmox.yaml: ""

  custom.css: ""

  custom.js: ""

  settings.yaml: |
    backgroundOpacity: 0.6
    cardBlur: md
    headerStyle: underlined
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    title: Bobo Homepage
    statusStyle: "dot"
    hideVersion: false
    disableUpdateCheck: false
    useEqualHeights: true
    layout:
      Home and Media:
        columns: 5
        style: row
        icon: mdi-folder-multiple-image
      Productivity:
        columns: 3
        style: row
        icon: mdi-folder-multiple-image
      Media Aquisition:
        columns: 5
        style: row
        icon: mdi-folder-multiple-image
      Infrastructure:
        columns: 5
        style: row
        icon: mdi-folder-multiple-image
      Network:
        columns: 3
        style: row
        icon: mdi-folder-multiple-image
      Monitoring:
        columns: 3
        style: row
        icon: mdi-folder-multiple-image
      Databases:
        columns: 1
        style: row
        icon: mdi-folder-multiple-image

  bookmarks.yaml: |
    - Proxmox:
        - Proxmox Helper Scripts:
            - abbr: PH
              icon: proxmox.png
              href: https://community-scripts.org
        - Proxmox Backup Server Instructions:
            - abbr: PB
              icon: proxmox-light.png
              href: https://4sysops.com/archives/proxmox-backup-server-install-and-configure/
        - Dietpi Proxmox Installer:
            - abbr: DP
              icon: https://images.icon-icons.com/195/PNG/256/OS_Linux_23399.png
              href: https://github.com/dazeb/proxmox-dietpi-installer
    - Reference:
        - Pimylifeup:
            - abbr: PL
              icon: https://pimylifeup.com/wp-content/uploads/2021/02/pimylifeup-square-logo.png
              href: https://pimylifeup.com
        - GitHub:
            - abbr: GH
              icon: github-light.png
              href: https://github.com/bobo-bc/
        - Giftful:
            - abbr: GF
              icon: https://dyr69yan0mo6n.cloudfront.net/giftful/images/logo_giftful.png?v=1
              href: https://giftful.com/stevenmeyer2
    - Design and Icons:
        - Material Design Pictogramer:
            - abbr: MD
              icon: https://pictogrammers.com/favicon.ico
              href: https://pictogrammers.com/library/mdi/
        - Dashboard Icons:
            - abbr: DI
              icon: homepage.png
              href: https://github.com/homarr-labs/dashboard-icons/tree/main/svg
    - Domain and DNS:
        - Webnames.ca:
            - abbr: WN
              icon: https://www.webnames.ca/favicon.ico
              href: https://www.webnames.ca
        - Cloudflare:
            - abbr: CF
              icon: cloudflare.png
              href: https://dash.cloudflare.com/login
    - Containerization:
        - Talos on Kubernetes:
            - abbr: TK
              icon: https://www.talos.dev/favicon.ico
              href: https://secsys.pages.dev/posts/talos/
        - Docker Swarm:
            - abbr: DS
              icon: docker-moby.png
              href: https://rpi4cluster.com/docker-swarm-intro/
        - Dockerholics:
            - abbr: DH
              icon: docker.png
              href: https://petersem.github.io/dockerholics/
  services.yaml: |
    - Home and Media:
        - HomeAssistant:
            icon: home-assistant.png
            href: https://homeassist.smeyer.ca
            description: home automation
        - Plex:
            icon: plex.png
            href: https://plex.smeyer.ca/
            description: Media Viewer
        - Immich:
            icon: immich.png
            href: https://pics.smeyer.ca/
            description: photo curation
        - Paperless-ngx:
            icon: paperless.png
            href: https://paperless.smeyer.ca/
            description: document mannagement      
        - Kavita:
            icon: kavita.png
            href: https://books.smeyer.ca/
            description: Book reader
    - Productivity:
        - Wikijs:
            icon: wikijs.png
            href: https://wiki.smeyer.ca/
            description: notes curation
        - Ghost:
            icon: ghost-light.png
            href: https://ghost.smeyer.ca/
            description: my nicer, newer blog
        - Drawio:
            icon: draw-io.png
            href: https://drawio.smeyer.ca/
            description: Drawing tool
        - GitHub Blog:
            icon: github-light.png
            href: https://smeyer.ca/
            description: my blog
        - PDFding:
            icon: pdfding-light.png
            href: https://pdf.smeyer.ca/
            description: pdf editing tool
        - IT-Tool:
            icon: it-tools.png
            href: https://tools.smeyer.ca/
            description: toolbox of goodness
    - Media Aquisition:
        - qBittorrent-vpn:
            icon: qbittorrent.png
            href: https://torrent.smeyer.ca/
            description: Downloader
        - Prowlarr:
            icon: prowlarr.png
            href: https://index.smeyer.ca/
            description: index management
        - Sonarr:
            icon: sonarr.png
            href: https://tv.smeyer.ca/
            description: Tv management
        - Radarr:
            icon: radarr.png
            href: https://movies.smeyer.ca/
            description: Movies management
        - Lidarr:
            icon: lidarr.png
            href: https://music.smeyer.ca/
            description: Music management
    - Infrastructure:
        - Proxmox:
            icon: proxmox.png
            href: https://pve.smeyer.ca/
            description: proxmox host
        - Proxmox Backup Server:
            icon: proxmox-light.png
            href: https://pbs.smeyer.ca/
            description: proxmox backup host
        - Longhorn:
            icon: longhorn.png
            href: https://longhorn.smeyer.ca/
            description: storage
        - Portainer:
            icon: portainer-alt.png
            href: https://portainer.smeyer.ca/
            description: k3s/docker management
        - Argo-CD:
            icon: argo-cd.png
            href: https://argo.smeyer.ca/
            description: App deployment
    - Network:
        - PocketID:
            icon: pocketid.png
            href: https://id.smeyer.ca/
            description: single signon authority
        - Unifi Gateway:
            icon: ubiquiti-unifi.png
            href: https://unifi.smeyer.ca/
            description: network router and DNS
        - Traefik Dashboard:
            icon: traefik.png
            href: https://traefik.smeyer.ca/dashboard/
            description: k3s reverse proxy
        - Hubble:
            icon: cilium-light.png
            href: https://hubble.smeyer.ca/
            description: cillium web ui
    - Monitoring:
        - Grafana:
            icon: grafana.png
            href: https://grafana.smeyer.ca/
            description: Monitoring
        - Uptime Kuma:
            icon: uptime-kuma.png
            href: https://uptime.smeyer.ca
            description: uptime tracking
        - Pulse Monitoring:
            icon: pulse.png
            href: https://pulse.smeyer.ca
            description: Pulse Monitoring
    - Databases:
        - Adminer:
            icon: adminer.png
            href: https://db.smeyer.ca/
            description: database management interface

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: google
        target: _blank
