apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  kubernetes.yaml: |
    mode: cluster

  docker.yaml: ""

  proxmox.yaml: ""

  custom.css: ""

  custom.js: ""

  settings.yaml: |
    backgroundOpacity: 0.6
    cardBlur: md
    headerStyle: underlined
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    title: Bobo Homepage
    statusStyle: "dot"
    hideVersion: false
    disableUpdateCheck: false
    useEqualHeights: true
    layout:
      Home and Media:
        columns: 4
        style: row
        icon: mdi-folder-multiple-image
      Productivity:
        columns: 5
        style: row
        icon: mdi-folder-multiple-image
      Media Aquisition:
        columns: 5
        style: row
        icon: mdi-folder-multiple-image
      Infrastructure:
        columns: 5
        style: row
        icon: mdi-folder-multiple-image
      Network:
        columns: 3
        style: row
        icon: mdi-folder-multiple-image
      Monitoring:
        columns: 3
        style: row
        icon: mdi-folder-multiple-image
      Databases:
        columns: 1
        style: row
        icon: mdi-folder-multiple-image

  bookmarks.yaml: |
    - Proxmox:
        - proxmox backup server install instructions:
            - abbr: pb
              icon: proxmox.png
              href: https://4sysops.com/archives/proxmox-backup-server-install-and-configure/
        - proxmox helper scripts:
            - abbr: ph
              icon: https://raw.githubusercontent.com/tteck/Proxmox/main/misc/images/logo.png
              href: https://community-scripts.github.io/ProxmoxVE/scripts
        - dietpi proxmox installer:
            - abbr: pi
              icon: https://e7.pngegg.com/pngimages/558/768/png-clipart-logo-debian-gnu-linux-computer-icons-linux.png
              href: https://github.com/dazeb/proxmox-dietpi-installer
        - dietpi lxc:
            - abbr: dx
              icon: https://www.unixmen.com/wp-content/uploads/2014/07/LXC.png
              href: https://dietpi.com/blog/?p=2642
    - Build:
        - Namecheap:
            - abbr: nr
              icon: https://images.seeklogo.com/logo-png/27/2/namecheap-logo-png_seeklogo-273737.png
              href: https://www.namecheap.com/
        - Cloudflare:
            - abbr: cf
              icon: cloudflare.png
              href: https://www.cloudflare.com/en-ca/
        - My GitHub:
            - abbr: GH
              icon: git.png
              href: https://github.com/bobo-bc/k3s
        - icons:
            - abbr: DR
              icon: homepage.png
              href: https://github.com/homarr-labs/dashboard-icons/tree/main/svg
    - Reference:
        - Dockerholics:
            - abbr: DH
              icon: docker.png
              href: https://petersem.github.io/dockerholics/
        - Swarm:
            - abbr: ds
              icon: docker-moby.png
              href: https://rpi4cluster.com/docker-swarm-intro/
        - Piupmylife:
            - abbr: UP
              icon: https://pimylifeup.com/wp-content/uploads/2021/02/pimylifeup-square-logo.png
              href: https://pimylifeup.com
        - Coursiv AI learning:
            - abbr: AI
              icon: https://blog.coursiv.io/api/media/file/coursiv-logo.svg
              href: https://coursiv.io/en

  services.yaml: |
    - Home and Media:
        - HomeAssistant:
            icon: home-assistant.png
            href: http://10.0.2.4:8123/
            description: home automation
        - Plex:
            icon: plex.png
            href: https://plex.smeyer.ca/
            description: Media Viewer
        - Kavita:
            icon: kavita.png
            href: https://books.smeyer.ca/
            description: Book reader
        - Immich:
            icon: immich.png
            href: https://pics.smeyer.ca/
            description: photo curation
        - Giftful:
            icon: https://dyr69yan0mo6n.cloudfront.net/giftful/images/logo_giftful.png?v=1
            href: https://giftful.com/stevenmeyer2
            description: gift registry of things that I covet
    - Productivity:
        - Wikijs:
            icon: wikijs.png
            href: https://wiki.smeyer.ca/
            description: notes curation
        - GitHub Blog:
            icon: github-light.png
            href: https://smeyer.ca/
            description: my blog
        - Ghost:
            icon: ghost-light.png
            href: https://ghost.smeyer.ca/
            description: my nicer, newer blog
        - Drawio:
            icon: draw-io.png
            href: https://drawio.smeyer.ca/
            description: Drawing tool
        - IT-Tool:
            icon: it-tools.png
            href: https://tools.smeyer.ca/
            description: toolbox of goodness
        - PDFding:
            icon: pdfding-light.png
            href: https://pdf.smeyer.ca/
            description: pdf editing tool
    - Media Aquisition:
        - qBittorrent-vpn:
            icon: qbittorrent.png
            href: https://torrent.smeyer.ca/
            description: Downloader
        - Sonarr:
            icon: sonarr.png
            href: https://tv.smeyer.ca/
            description: Tv management
        - Radarr:
            icon: radarr.png
            href: https://movies.smeyer.ca/
            description: Movies management
        - Lidarr:
            icon: lidarr.png
            href: https://music.smeyer.ca/
            description: Music management
        - Prowlarr:
            icon: prowlarr.png
            href: https://index.smeyer.ca/
            description: index management
    - Infrastructure:
        - Proxmox:
            icon: proxmox.png
            href: https://pve.smeyer.ca/
            description: proxmox host
        - Proxmox Backup Server:
            icon: proxmox-light.png
            href: https://pbs.smeyer.ca/
            description: proxmox backup host
        - Longhorn:
            icon: longhorn.png
            href: https://longhorn.smeyer.ca/
            description: storage
        - Portainer:
            icon: portainer-alt.png
            href: https://portainer.smeyer.ca/
            description: k3s/docker management
        - Argo-CD:
            icon: argo-cd.png
            href: https://argo.smeyer.ca/
            description: App deployment
    - Network:
        - Unifi Gateway:
            icon: ubiquiti-unifi.png
            href: https://unifi.smeyer.ca/
            description: network router and DNS
        - Traefik Dashboard:
            icon: traefik.png
            href: https://traefik.smeyer.ca/dashboard/
            description: k3s reverse proxy
        - Hubble:
            icon: cilium-light.png
            href: https://hubble.smeyer.ca/
            description: cillium web ui
    - Monitoring:
        - Grafana:
            icon: grafana.png
            href: https://grafana.smeyer.ca/
            description: Monitoring
        - Uptime Kuma:
            icon: uptime-kuma.png
            href: https://uptime.smeyer.ca
            description: uptime tracking
        - Pulse Monitoring:
            icon: pulse.png
            href: http://10.0.0.11:7655
            description: Pulse Monitoring
    - Databases:
        - Adminer:
            icon: adminer.png
            href: https://db.smeyer.ca/
            description: database management interface

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: google
        target: _blank
