# Middleware: redirect HTTP -> HTTPS
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prowlarr-redirect-https
  namespace: media
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
# IngressRoute for HTTPS
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`index.smeyer.ca`)
      kind: Rule
      services:
        - name: prowlarr
          port: 9696
  tls:
    secretName: wildcard-smeyer-ca-tls
---
# IngressRoute for HTTP (only used for redirect to HTTPS)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-http
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`index.smeyer.ca`)
      kind: Rule
      middlewares:
        - name: prowlarr-redirect-https
      services:
        - name: prowwlarr
          port: 9696
