apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://immich-app.github.io/immich-charts'
    chart: immich
    targetRevision: 0.8.1
    helm:
      values: |
        immich:
          persistence:
            library:
              existingClaim: "immich-library-pvc"      
        # Bundled Postgres with AI extension
        postgresql:
          enabled: true
          image:
            repository: tensorchord/pgvecto-rs
            tag: pg14-v0.2.0
          persistence:
            enabled: true
            storageClass: "longhorn"
            size: 10Gi
        
        redis:
          enabled: true
          
        machine-learning:
          enabled: true
          persistence:
            cache:
              enabled: true
              type: emptyDir
          resources:
            limits:
              memory: 2048Mi
            requests:
              memory: 1024Mi

        ingress:
          main:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - host: immich.smeyer.ca
                paths:
                  - path: /
            tls:
              - secretName: wildcard-smeyer-ca-tls
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
