apiVersion: ENC[AES256_GCM,data:N4Y=,iv:6O9AKqIxjdlL1iNie/orezAkZ2yZ1oFI5WB43pqYCx4=,tag:kvWXApwAhDFSOMrp0LbSoA==,type:str]
kind: ENC[AES256_GCM,data:tLOQc3ar,iv:PbENbcw+cu/DDu8X1yFfFJs3LRhuKp8bgBOVoyqmRTg=,tag:f4NM/cfduzQvWcBDAGMuRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8xqk+ItwPr7woVYAeqJg8A==,iv:0pZ4YS/gobU0FzYVtgdPGWbNJtxk1tGR6rWtM0uylG4=,tag:2toXs+6R75uqS+ltY4/sQQ==,type:str]
    namespace: ENC[AES256_GCM,data:Buvk1Zij,iv:0J1e7Zgy687RXG1Uvqb57PvEgm5yb/PzZTgWIf9Ixas=,tag:xhY53n3sUoi2qMCVVnthlw==,type:str]
type: ENC[AES256_GCM,data:tZOb4NhO,iv:LMMEmqeIQibJENx5oqR2A9ZrumiZRy0Ibkx3eEO7txo=,tag:VbS4X60glDyObV+odyFg6g==,type:str]
stringData:
    #ENC[AES256_GCM,data:rfPuJJ+qIMwwG3clyXAcQgGblQ/tbAw788OAZZ2RFwXfkib8nd6iZ3X39Rgmami4Lm30x2ZZx+EIGT89UA==,iv:7rd0a4urtYy8A2eeB7dd8X8riREWoGXo+y8lXcBljLk=,tag:DBzlc+f42rjUqc+MwrtqKw==,type:comment]
    DB_USERNAME: ENC[AES256_GCM,data:H8gkGHt4cc8=,iv:kFM1eam+7orqz3+M+L1d3uP875ToZN1Tz8Mi1HKRywg=,tag:JteJuWSkEwBkt7Y5GTmboQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Ij+TQARgQrXo,iv:JpsFDvBgXWUnhKl4m36nWnFT0nFwamm97gLbW2Fid8s=,tag:/MlU3MuzCfQtPM9CBpRARQ==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:GTa4tyw8,iv:ztTmlSqfKi51enFWdFOYorC8NwPYo80x76JCchYiHes=,tag:v2tXo7j+soPblQUtm0of1g==,type:str]
    #ENC[AES256_GCM,data:8oWI+TpH5ZvzPT9DkTcVg0bDHoPAcLwJhRU4ClMh0JxHtWewb/d7kFYwj8b7fL+TPhKzPdLtrQ==,iv:hNTXk5cZGx03mGMpzthGjEUTbq2r0Tu4WhV6yGwLqBk=,tag:YiTObWp3cTwsr/q3Oad2Gw==,type:comment]
    #ENC[AES256_GCM,data:Cp2cv1/rGibpnLcEG/IhErjckwSqvIxFVfM7dINN+rnO9qJPR/AyHY37g8YSDFVQ4bMqKUYeLFV/9+xntLsf5Z4RoJAvgzfNzRXXh7Yj+gg+,iv:Dhns2HzrE6tLnVC2krh9VRMSqPk2oA8R0aBVFZ+fpAg=,tag:JFBnXubrQWv496I0MzQouw==,type:comment]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMllZamZWOGZ5cmQyaEVu
            eWM1UzZlN0l1UEJ5d2RiS0YrRURNZ2h4bGx3Clp2blRIZkZ0dGZhd0sxS0Jibkg4
            NW5XdEdPaTh0eFZvVC9rYmlaZWVjVW8KLS0tIEg4UHhXMDdIWDVIUGl2blkxVFhj
            UEVvTmY4b0d1Z243TXNnZFBHTmdaSlEKBlotqX61J6ptSfqHRMcAneqBLHLXny8i
            EF2h1pRu6fFfJPNAsYGh/poshFkCf7ajZsE/H0q3nwmBI75E6wtz2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T03:30:08Z"
    mac: ENC[AES256_GCM,data:xpqnm1ht4J8Nvko4bMUQsSdg3UloTmfn0TpB2oxGinqv8koxj6c5xXbR7aoj6+emmB6nmUaj7bXzYUYKAeSatfuEc61Ksqp23lil3d3L3ykYfB3QlPzm5iwJ0CEuVkWc/Wyd7ig9E2LnGITgeMEJ21QIx9eRCkqZj/++SiG1wq8=,iv:fxltKMQZPyHCR/kPyL6gXvf3XkKwB5pZhzCXCceoywo=,tag:w1xSA8ulVA2Jk0LLJIqehA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
