apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawio
  namespace: drawio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drawio
  template:
    metadata:
      labels:
        app: drawio
    spec:
      containers:
        - name: drawio
          image: jgraph/drawio:29.6.10 # Use a specific version for stability
          ports:
            - containerPort: 8080
          env:
            # This helps Traefik know how to build URLs inside the app
            - name: DRAWIO_SERVER_URL
              value: "https://drawio.smeyer.ca"
