apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pdfding-https
  namespace: pdfding
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pdf.smeyer.ca`)
      kind: Rule
      services:
        - name: pdfding
          port: 80
  tls:
    secretName: wildcard-smeyer-ca-tls
