env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: pdfding-secrets
                  key: SECRET_KEY
            # PocketID OIDC
            - name: OIDC_ENABLE
              value: "TRUE"
            - name: OIDC_PROVIDER_NAME
              value: "pocketid"
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: pdfding-secrets
                  key: OIDC_CLIENT_ID
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: pdfding-secrets
                  key: OIDC_CLIENT_SECRET
            - name: OIDC_AUTH_URL
              value: "https://id.smeyer.ca/authorize"
            - name: OIDC_TOKEN_ENDPOINT
              value: "https://id.smeyer.ca/api/oidc/token"
            - name: OIDC_USERINFO_ENDPOINT
              value: "https://id.smeyer.ca/api/oidc/userinfo"
            - name: OIDC_JWKS_ENDPOINT
              value: "https://id.smeyer.ca/api/oidc/jwks"
            - name: OIDC_END_SESSION_ENDPOINT
              value: "https://id.smeyer.ca/api/oidc/end-session"
            # App config
            - name: CSRF_COOKIE_SECURE
              value: "TRUE"
            - name: DEBUG
              value: "FALSE"
            - name: HOST_NAME
              value: "pdf.smeyer.ca"
            - name: SESSION_COOKIE_SECURE
              value: "TRUE"
            - name: CSRF_TRUSTED_ORIGINS
              value: "https://pdf.smeyer.ca"
            - name: USE_X_FORWARDED_HOST
              value: "True"
            - name: SECURE_PROXY_SSL_HEADER
              value: "HTTP_X_FORWARDED_PROTO,https"
            - name: ALLOWED_HOSTS
              value: "pdf.smeyer.ca,localhost,127.0.0.1"
