apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=2
  nfs:
    path: "/"  # Use root if /mnt/data fails; map subfolders in the Pod
    server: 10.0.0.5

