apiVersion: ENC[AES256_GCM,data:fHE=,iv:zQwhvnpIUtLPILWBt2c4FJXgYcm9sYjbOTx+6sOLY3Y=,tag:/elgkpcqa5B8nGBiUGRakA==,type:str]
kind: ENC[AES256_GCM,data:/r+aOGvi,iv:q7t3ONZ02gOxh1QTwmsQ+lZgy6skuue9dIDSAzxErwY=,tag:AxlDchkvOvJVh/D2HzaAwQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ENhQ4kJIMY5A8qW6,iv:J2qPMzRuKmZfcVIai9sK3l0V8uVszcQHOoQLdoR3j/I=,tag:hQamXLqtTvi2vYDNCzVQdA==,type:str]
    namespace: ENC[AES256_GCM,data:VmwshOw=,iv:/8WlkBTNw8/0GlI3v9OMnucY1ypdAnWsb4DUlEMsixA=,tag:+RZtaBDuaNnVopL6ElanlA==,type:str]
type: ENC[AES256_GCM,data:8wR/aXOw,iv:g4U/0IqCe4wGkrRXiatO/3CkUiVEruZ6waddGIkbEAA=,tag:s1xK2fqv0EnBC+avdgvTeQ==,type:str]
stringData:
    PULSE_AUTH_USER: ENC[AES256_GCM,data:P7ADsh0=,iv:OMFZJqjMCrJH46NAfLAJ4sgkcmRwZ0i67I1BQaxtto0=,tag:Pu4RgByas5dE5L7kEIOIRA==,type:str]
    PULSE_AUTH_PASS: ENC[AES256_GCM,data:ux5aknnYA/04,iv:RvRLzBPGf8TpCUWO25LldQ5f0HYLEzacUZ/oJlC2tJc=,tag:8C/q4QnSVIJ2LzT2CihxWg==,type:str]
    API_TOKEN: ENC[AES256_GCM,data:AL0DxqGhzgF+,iv:Kr2J+Gr8ntLU6x4sp0WD5rCB7b1wX/jl2Wfk6ES+060=,tag:yXrkavuLh2ogpJSVJWg3Qg==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLR0srZUxhUE4vSWZuSnM5
            bDZwdUhyaGU1ZjFzc255Vm0wRzd0VGFuencwCkxpQnh0V1ZJeEo0SFBUS1pGNmpy
            biswdUZab0RsOTF6RjEyTldYS2VwbU0KLS0tIEhLdmFNZlpCUGNZT2JacGQ3OW1U
            QkhRcXVzanhpUWFXZ2tzZTl2WG9yWWcKIuUXAbyv/z2/57HXfVXOmbra6iYm5CP+
            tcY2fMySKX9bbWpzSK85I4KPef71/uRqUQtLfCaR1yF9TppToI9Avw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T03:29:41Z"
    mac: ENC[AES256_GCM,data:NYowhhZnWwXGr8wdOJwUB2PiKrfvAPyUhqvzK7jus86I5Mq8RheJkxPr1sHgAEkj5yaBC1F3/ZRgLlA06eUq5U2vOg+HzY9CQHJ2ar0g/pkxF5kkKFq61oT7dCrWg5mbwl/BQoivAxHMeS5VLhZylJS7+WtyiPMadbr79L9iDkc=,iv:9VVO0pUZ08gV1geMBtPtymkvJwtLVr1xVLJ9Iggp8BU=,tag:kvGVYi2aofJXBjuov71Wfw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
