apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: it-tools
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bobo-bc/talos.git # Point to your own repo
    targetRevision: HEAD
    path: manifests/it-tools # Point to the folder where you'll put the YAML below
  destination:
    server: https://kubernetes.default.svc
    namespace: it-tools
  ignoreDifferences:             # ADD THIS BLOCK
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec
        - /metadata
  syncPolicy:
    automated:
      prune: false               # CHANGE from true to false
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
