
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-secrets
  namespace: ghost
spec:
  encryptedData:
    database__connection__database: AgCT23FTqdAkrxX9Fs120ZZ93Rm8D2ZoG2BiGzxEWREiYJFD/6aVdtXU/eZv0UVD9Z$
    database__connection__host: AgCCdh/hu1wKBXlLXrvS0dOiNUG0unzt6/rC+lgYyfhYxfXl5Uj4vsHoX+R1MaeGhmAJ05$
    database__connection__password: AgBuRod1ANVAf/hc2wAFtfriz/WyuutjOMP73Hk9gHK6EMpEcX6/uAtg70KLK+Mord$
    database__connection__port: AgC4rLrToDcEcc4zGep0LJPQKgP0mO+h9y2sstjAfmxDN7fSHiW/jfoN1/VKDZmzUK8RCV$
    database__connection__user: AgC72+0n7qahD7JTGWuG2P2TjSjBlkxgDlxvWPk64HJ5b+PiF5AjPgVaMo3JzFWQDmvAbV$
    mailgun-password: AgBShOp3ISslYruf3rNvqqOzV1tHSWTAodoFCASlQ4Oen5Ykf/O4RBF2pShLgORDSmSPhxHpez8jv8p7$
  template:
    metadata:
      name: ghost-secrets
      namespace: ghost
    type: Opaque
