apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-secrets
  namespace: ghost
spec:
  encryptedData:
    database_connection_database: AgB+ChOK3FrloQUL5RCUeIlPr7Xb7UVfUNYCdMOTLkkcs/AekESikAzaM2fBYZeVN6a3$
    database_connection_host: AgDoKSL3RYjmc2tWAk/hsYfkbNdJ9xB2Gp7qYdfxiHInTg3gUXcZDGiMfz79lUuBjXX9pCKq$
    database_connection_password: AgCiAecUwnr+qkQRuj0ULTf/7Mil9yZIA+bsIJqPh8We5IFziAfHyBE2Pktklcdg7lCc$
    database_connection_port: AgBoD5EwwPO1C8Vg2CYEdIbsA8We326zNmn1hIRuL63qTI4a8i9IA1Rq4UQpREkY5WMIkCJ5$
    database_connection_user: AgAtPYm6Wf6SMJImyv7BB7ic2GWGu2kwEU9OytYT1LL+ekgYcncfC4d+Bbm6lVuqcBYhPyzB$
    mailgun-password: AgCOU3k4SNqW5SC6st9AnsxFAGruh3hH5xj7ijAY9zglvEHiIuUQ0or3tU4NetHtIWkC4vifX4Pbm6CT$
  template:
    metadata:
      name: ghost-secrets
      namespace: ghost
    type: Opaque
