---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-secrets
  namespace: ghost
spec:
  encryptedData:
    database_connection_database: AgCT23FTqdAkrxX9Fs120ZZ93Rm8D2ZoG2BiGzxEWREiYJFD/6aVdtXU/eZv0UVD9ZL/$
    database_connection_host: AgCCdh/hu1wKBXlLXrvS0dOiNUG0unzt6/rC+lgYyfhYxfXl5Uj4vsHoX+R1MaeGhmAJ05CV$
    database_connection_password: AgBuRod1ANVAf/hc2wAFtfriz/WyuutjOMP73Hk9gHK6EMpEcX6/uAtg70KLK+MordTr$
    database_connection_port: AgC4rLrToDcEcc4zGep0LJPQKgP0mO+h9y2sstjAfmxDN7fSHiW/jfoN1/VKDZmzUK8RCVyr$
    database_connection_user: AgC72+0n7qahD7JTGWuG2P2TjSjBlkxgDlxvWPk64HJ5b+PiF5AjPgVaMo3JzFWQDmvAbVGQ$
    mailgun-password: AgBShOp3ISslYruf3rNvqqOzV1tHSWTAodoFCASlQ4Oen5Ykf/O4RBF2pShLgORDSmSPhxHpez8jv8p7$
  template:
    metadata:
      name: ghost-secrets
      namespace: ghost
    type: Opaque
