#ENC[AES256_GCM,data:2AM0ZOtfU0KhpHRDliXiyt9iDycZmQuwsdmoRlxBovid2HLjjuIgs9uVhJ7k,iv:9NSITVu669BXduvGoTocSeihERDq1knvQC0yfYeGJjQ=,tag:IvRddQTAs4U2zSO8woCOfg==,type:comment]
apiVersion: ENC[AES256_GCM,data:xYc=,iv:qbplXyFm/DIGZN8m59l6NomZsCuCBPWslNsAyGffvyw=,tag:kz97fp1QnCFaUt7soqlKYw==,type:str]
kind: ENC[AES256_GCM,data:jI1F+qRx,iv:W5IIFMZwM4CF7xD5Dn6iE0RiUXsC+EuXJH6aP1iyZ9I=,tag:yAgRSm5p4qhp+u3Bij+bDQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xRfvTOHiuc+ME/FhEw==,iv:IzVVUysFIaP3k/k5QmfbyEdOpN7GWUHjXZ9PapavZGI=,tag:sqAME7c5LV/9lV3TE0m6Kw==,type:str]
    namespace: ENC[AES256_GCM,data:NmWAeVA=,iv:s4mZ7GvUMWC3yyuDOG9yusReAnpX03TVjSbsj5EeYzs=,tag:Obe8koZ+qpRrsRf5VLwoMw==,type:str]
type: ENC[AES256_GCM,data:CcCWNRA+,iv:wR7NhIrffgN32DkX1bzkDpk7e3cCH5CZm7bUWGPHIbc=,tag:xqGZcdu7pfn46f45R8ZLwg==,type:str]
stringData:
    mailgun-password: ENC[AES256_GCM,data:XJZuiLq7paiStGeGBP9/S0AtDzU9Nu8lqcdvuI76ZTYT1FRbFZsIV/uH/+SS8FHxWPU=,iv:SHwirlEA/ff5Vikv1SGigfpb7e8sjnjczjh7Mc/UlRY=,tag:szfS54xWQ5vpZ4qe3CYrvw==,type:str]
    database__connection__host: ENC[AES256_GCM,data:iFEeKy7W4V+N,iv:Mol1qbXkkJ1qW89zmkxlq40/4BeGQnPaMcQr3np1/OM=,tag:UW26w/4s5T7JGRKYp9nj7w==,type:str]
    database__connection__port: ENC[AES256_GCM,data:uGa0uQ==,iv:QsMq8mWBGFUhaD479l28tcEL2KipfvGO6Y4GJob7zzg=,tag:DV2UOHjUtC9n6lHKB5Z+Ng==,type:str]
    database__connection__database: ENC[AES256_GCM,data:hfsT3XI=,iv:wS6N4vQDMz085JvZSwO1K5Mo6rSnFr7G7Pt2xQx0RcQ=,tag:qbXZQgYSfyjRrVVQ96lZOg==,type:str]
    database__connection__user: ENC[AES256_GCM,data:L3aoI5I=,iv:DU2AfAQGgCpT34QxsNBGnyaIgAGqd9aYkzZJIRZvbpw=,tag:I/b30RuG/hmvxVXIDTGs1w==,type:str]
    database__connection__password: ENC[AES256_GCM,data:fqq2sWitmRum,iv:d68U5F+xK0zmAR2uPxuEpSTEz0huzkiYLTCjmCwrAMs=,tag:bCTToxe3okiDZTq+n9PD6w==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYmk5aWpZaEVhbUF5YXR0
            bTh5dE1GVWp1SUJJKy9LZlptNXNoUENmc3hFClFuZVZsbkkxb0pPMVFSektnSHNE
            VHRGeWJtQkMzYVdYQlJrd2hDZHhaT1EKLS0tIFZ1SmlNSDl1anZENEYyemdUREVQ
            QUZwWUVPVHFmOU1IbUllK3JwVEdpM0UK6u5WQ9PcmRa7uyVNfESMTkosYV5dMpTw
            Qnjy04PWU7HLRzUP/AzIPUGNFTHCjyls2dF7SmVXMyTIv5UhXjek+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T23:41:41Z"
    mac: ENC[AES256_GCM,data:iW4f0BO8MGA/eUi4uuS+Ms9YU1m9lteMkuQuhlWBX6u6XkQ0BBoo2P4Za6bYamtYVbqagBbyBe/0/Wn2+8gMirHTrcvoL4D6mDtNRcO3bsoaeoOxW3BjjLR/voKhp19zVVVQNGuJokbIYHZlveneJ2Ws5rYROUO7YOmYmYTXlMM=,iv:eewsA5Hpt7F4u+2zTUvrvvOFuxeFJsfqjMuKAtUGygU=,tag:o/XxqT3ZfE3zCWw5YqUr/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
