apiVersion: ENC[AES256_GCM,data:EiA=,iv:T2tCIC8f9AbeWzGOXi4owe10lrxAwpyj0BvAq3H36d0=,tag:3+x+Bi7gnVr6Fy4Je1/DPQ==,type:str]
kind: ENC[AES256_GCM,data:3mopilpS,iv:+dQmF7A1ejyZC7KToVv1iOaIs0WmyQNxhKXjs8K2GQ4=,tag:8udI23bO2L3bLYTdodHUig==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kB1Fy6WNRS3BZxpwzA==,iv:JYBOEQKORXVa3IPQjIHqXZR+rmOFHZfpLFeXOYkn/wM=,tag:OdmgP49KGWLfpRYlfgJr4w==,type:str]
    namespace: ENC[AES256_GCM,data:WN/oRaY=,iv:reGUMCfzZ5pHRxZpLSeMrhZvDbJnfIEe2GXbZqKJpNo=,tag:n007YVNEeSzQb41AMCXHEQ==,type:str]
type: ENC[AES256_GCM,data:7vB96Mna,iv:pZrrIsp/AyoWaW341U2LDR3U0PFWt5UUnQrTdA3OoU0=,tag:Fiun366MJ83AALlpoA6+1Q==,type:str]
stringData:
    #ENC[AES256_GCM,data:DzkKBmKNuDBX/oKxylMnjv/c,iv:XiRlK0BQXGYKGP6Mf8UpK6CH/swj9Y10EtZsRdrDWiQ=,tag:Dv+FXsTm1YkMkl0WLvmpaA==,type:comment]
    config.production.json: ENC[AES256_GCM,data:cb+0NUJn9UouUOw3Gn6AqHNLoaKo3nHxP7y/6Pn5rH2BdK1YqKrbkyaDOX3S1Dpi2JDtaG2uQtVa4E4b8IThMgmw4tACDa+9gisC8jHEoGB9Pc2E8G5cpxQDzZw6UPtSpFQ7k5GM21gsXizMmsmtQbXafjyGZB+a5NjlKwklVtKvt49kgzTp+sFhEEJ6TBhHYLfHrv+0LeqcT7zRfF9Fx9obCEdtHgpMXpfrnxu/Nm1VWeSaIzVuDq+FWlcgK+mgffrHXLKvhJHadK/c7Txq4Td8Ezsifd32HTKt2v80GOS88qGieNjhaPoHdpf/+f3zoedQj+gpSiwVCeXJvXpv6R4WYOpogRqkx8Jd+r6j8UimJvjRuBna6Qk6DkF1eHhZ/tNTC3JTal8ToVQGqDlMlXjMiP7PMxLK/C1GVVBVwrehLYKOpywdBcR/9R9Xu5UMV//ivRKgqo9cSvYjMNC4tmdtuXzm8CnILTG2l9a7Q5YF3Yj7mQb2bGdPiRZ5ZKbNlvBi69r+AQ11dxoVdbTrgD9vijDRdVa29+8HOLcxN//WtVRqnf4qI748C0bZlLDxbBjZiTx5VLYoOUOV2/i3p41HahgW//1Uca9EGMK/Hd1EtEu4HNsmPjorYtpIN3mDWYOnudkwbjrqZPyjUoqEcepv5L0ZBd1hIC1SVteuJEoMBYKvLOl6R+dnF7gO3ZiSCjNTmHbz/vE05/jnpdXDxEDbdcVwzP22Tm57GZw8ZqUfQfep8o5o3XB5YSt0QnUcADnmjVme04IfEz8MJK7ndGRBeDjtAkWrASZKBypGhf4bDs9saIJ4Y2kK5IXI7nHB5f62ZKkr2wGUZ/VK,iv:8+pZygTLnnz7J1ODH3DMVF9mnQhtXKDanCxQfJd78/c=,tag:Cf//PDLHQ6XBFbHngofwcA==,type:str]
    #ENC[AES256_GCM,data:OAFuMFGuNn1gtEzjCskH,iv:8h7gyDf/EyHvz/Aw+PigqzhfH7V1qJ/+imk3Xesckqg=,tag:MZuYQC9cfIcNt/cjOmXTwg==,type:comment]
    MYSQL_DATABASE: ENC[AES256_GCM,data:jNVAULs=,iv:eEuOnEoenSCdVISZjqhjU5ZxULouvHuN+dMgJ2xA1h0=,tag:kHcj8+QBS1p1QmCNa6H1Wg==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:xyID4Z0=,iv:o+UiETZimil3i906CkwXWUCjuiI/Ut4utHuK6l3893g=,tag:JDFs4eGvHpnNVLSYIK9taw==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:83U2BPfq+EMOB9TH76C3MqEoBrnm3U/8rkTyoXGQt4HKQWcNfwCBkjeEXBAYFr4WFI0=,iv:9v6MLxUgy0yAtL8F5H+40tpkHgzwfN6d7xN9IFRrU/k=,tag:TtosoWGDvbSHG6c5ka6EtA==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:RNxfVjGJaJFIEbFSlNgiddSY6w5e+Tt62wJcR3SY6h3yQ+S4oVV61BTwwdA9K5sGzxE=,iv:cWjBPL09VpY3fYhdgRX/yGupZoepud+qX0YIfff6toc=,tag:ErtCxe54919xtO71YajWhw==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWkpnUEY3ZXFCcG1UcFBD
            VkxuRVVJcWJnZkpOQkp1bEd4T0xZUzgxYUdjCllHQlo5bXpzOE93OGdlMEhKZjlO
            a3dFalZYZXJjNC9TRU9GckJablJ0elEKLS0tIFJSZFJwVDh3YndhV1RjSVpaVXVV
            cFp0ZHZFK2FCUVczb1NUWWtXRjdaWUUKOYNnN6zulrSXt0D8ozvH5un99Z95G+CQ
            SuYlOvv9uii2JsTKFzTroprLllf9yk7vsqXBw6kGUiJ5Vj7f/xrd0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T01:23:48Z"
    mac: ENC[AES256_GCM,data:UfdsBH1qft14OdTx/NXHC2a9eTiuI89BazT+1zYrRRQf3r28ju7TJRfD/ezwE+Odsmzowi6al1kOH65j8YfvMrQd46/ZTB0koTDevO04pegbP5ED1qNuD8D1Z3r8auguAq2vXS+NO7ezh32BcCW24rrptYaFkOLfCtNAKQ/f9JA=,iv:tm4BVO45ecVXJ1GNJflaUEnDoBXOUU3B71zx9fTTEGo=,tag:QzSTRuWQ/8i2zrUmAFYZ/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
