apiVersion: ENC[AES256_GCM,data:BWI=,iv:wuyjReZ9QH7BlB0hwxp3FFUG7ov/WAV6Dj8n3rMr4kY=,tag:HUF8/pa83sUxJyUl2KzsAA==,type:str]
kind: ENC[AES256_GCM,data:478pWjFM,iv:HEmaaVoagtbPKafr8DZxA9mivBpxNKF4A7Hh+/Ycx7M=,tag:0f4tLqHbeUwzmuoPxqxxyg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rZh2slIoDfWGRyXyGA==,iv:N3gLEE/yWKtArfsbIQZfW5/HmhgqOqNGkBAzMDzPM0Y=,tag:wwzyDudz4JgeHk9DcNKmAw==,type:str]
    namespace: ENC[AES256_GCM,data:gO/FPOY=,iv:jBWzScaX1nW5KE3EdnIzip2cHQ/mDe3J21VTXroGu44=,tag:PSntb35EOna/aT5ToNHYNw==,type:str]
type: ENC[AES256_GCM,data:XsJIfHZf,iv:V9HBdwLZvtsclCYiwyP3eujNNMFDxuZp2D7BPRDNG8g=,tag:H5BbvjtYAxU5076dBZITPA==,type:str]
stringData:
    #ENC[AES256_GCM,data:JMyXysZDF7pALd1chrOk5aLp,iv:DkZN2LDa0PeCRYIEHKpKVBQ3AqSYhSeHmx7VuBxky68=,tag:WetXL3AuGRyAJ/p2xWY2rg==,type:comment]
    config.production.json: ENC[AES256_GCM,data:JpaQiJjCguU6Uc0WkIF1OFKfc1Cp9NKOvOdENJ1XCoDouARz6dgNhe4a9sWZwFPiUx8aABJm6wWswAP/HQ069zPZibeltc9H5C1BhmoXQ7GtJE2QiqZX9M+u9GcccQ97/M4Kh8OsnajCDmqRIi7WG7HeytJyzHmxvlmTt7jeeqa4CwW9tIhfPbUvPvIXh0i2tLQ0S/xGKKaB3du/gDv/5/O5keRClMtOo33T7eq2Zl0YqSdUm2u1TlXqXted7wvagFNNPesVbhx80F/3t9qiJ7NixNMzZ5VfBsNn9hARzRSEpLVO5zSSR8Nle2Z6gHFq7hBrb1IJIUsDAyIk1pZXagRR2Mp4Hqff7OvMLazkvp9a+cTRJCotcNnzzqXBr5H//BzmEGea5gfmO74B3I+Fmqfla4tmcg5rYFJvCkJNb/OwbkFERbQGOK7281by0uayKPLuaHPwsThz7CAdjHlypPazIQBavKg6fzDb5aR/srOX6EU0FTgnj5C7o/yKd3BgQ75cNg1URRJ4NIOjTouOp5zAeRD2H7YNNQKykvb8v+RA8vf3VhPMFwiJ3kzQN2vsc9V1aRsxyiMaZyEdku6Wj9AYXWFYX9BUKu6pCHikgalP60TwkigIXcoDc1Spri6ZJTRE6xYEXtCIlGh44cP5+Nk1CkbjEU12hKq0GmYceMy80x1ScD74xz7UuN0IUam82xJsq2KjtCQXYbkxH9oK0kvRgadW3bSAbidN4XE3VrqFyC9kr+N7AlXU6SQeVh+dz7DkaoikL3OgZvT5jL7jaUnnHA==,iv:c3RGoNPbMe/wgf/KdfeZk9U2EZXwyazNYh1YAzHTWYE=,tag:fjvzOL1a20m5QhVwXuXQYQ==,type:str]
    #ENC[AES256_GCM,data:doqrqda2CHxhtRxZr+Ak,iv:6t+kt3ZBxgsdY/J2txNhq3P4u6/hG6TtrhBimi3AV8Y=,tag:Gj4YrjDQI//oywUMz+1IYA==,type:comment]
    MYSQL_DATABASE: ENC[AES256_GCM,data:22CzcVM=,iv:+M4qBir5vBoH+HVrcPUZtaoiSCqcJZBwbrjaD3LPaVw=,tag:5rLNmwcMtAuroG3r7lKmUQ==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:MnxTF04=,iv:zMKnD01esF7rErxrTz95/OSHsdQzYop5HQoX115QJuU=,tag:D0Ce16GRNKpqpG0ivDYSoA==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:0uazUeNNhe7Sv8XH2p9dtJyxLnoVJfHr0KfnAlXC0m0R98/FhEkvCsPOQ71A1+PmFFE=,iv:QMDKdD/f9YYwDmGE4v6QbO3O9Ph1nl+L5WKKt4I9OrQ=,tag:cMdvdVf5boqolCg8dqE0HA==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:310BXcI2eK2p+CF6uTTVakN+zk8kqP1r6eZ5KC0/+1/Fiddl+SOCCaeqCUrORAEGvSs=,iv:1jqmmvTp5mA0VUPEWGxkRyivcjYEIMx4BcnkiSuZYQk=,tag:lvoaQ0IZtcaoYSA2Gggs5Q==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYUxPbkdMcDNsVHoxT1c4
            Y0d5SjNlVWFhUjJjdVFJU21oS2sxZVA2aFNFCm54VTlURnNBVHVHSjA4N05Vb3cz
            M3BYY0h5SzJtZUpxR1cwOVhHQmg1dWMKLS0tIEpPNGJudG96YnNaTCtEYk9XQytl
            VWtySFZKSWpLdlcvWTZwekJleUpSMHMKXZX3/iSj2xQNck17PUmxbWSxzVEcstw5
            1IlCZBphlwaVGKv+MzPGEw3FQ4IVaQvdZhqsGzJmFPKvjioCYNkBcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T01:07:40Z"
    mac: ENC[AES256_GCM,data:ZVyFtrmL8wyU611XF2uakI3psQ0VBSZVWakgNueNVisMXe8hkD9UZUogf29RGt4FDup2dOuKn7mQqEqm4sgscoSclhd27EsfGh1piCKxh2IipHU2fBdjciYbS4kfcPu5Xv3AFdtMH/4XMtpiKxUH1ZGqAsR9xxEWCNhjw9GRnbw=,iv:ya7KxFrzX5wo8LHAQtFHdYBsS5UPNoFUWm6X1hpvrUI=,tag:zflQmJLuwJa16ZRG8i/nVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
