apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`hubble.smeyer.ca`)
    kind: Rule
    middlewares:
      - name: pocketid-auth
        namespace: traefik-forward-auth
    services:
      - name: hubble-ui
        port: 80
  tls:
    secretName: wildcard-smeyer-ca-tls 
