apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging # Use staging first so you don't get rate-limited!
spec:
  acme:
    email: your-email@example.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - dns01:
        cloudflare:
          email: stevenfmeyer@me.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
