apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv # Must match volumeName in your PVC
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  nfs:
    server: 10.0.0.5 # Replace with your TrueNAS/Proxmox IP
    path: / # Replace with your actual NFS export path
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=2
