apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://k8s-at-home.com/charts/ # Or the modern 'bjw-s' charts
    chart: sonarr
    targetRevision: 16.2.0
    helm:
      values: |
        image:
          repository: linuxserver/sonarr
          tag: latest
        
        # 1. THE "BRAIN" (Longhorn)
        persistence:
          config:
            enabled: true
            storageClass: "longhorn"
            size: 2Gi
            accessMode: ReadWriteOnce

          # 2. THE "MEDIA" (NFS)
          media:
            enabled: true
            type: custom
            volumeSpec:
              nfs:
                server: 10.0.0.5  # Your NFS Server IP
                path: /
            mountPath: /tv

        # 3. THE "ACCESS" (Traefik)
        ingress:
          main:
            enabled: true
            ingressClassName: traefik
            hosts:
              - host: tv.smeyer.ca
                paths:
                  - path: /
                    pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
