apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-static
provisioner: kubernetes.io/no-provisioner # Tells K8s: "I'll handle the PV manually"
reclaimPolicy: Retain
volumeBindingMode: Immediate
