#ENC[AES256_GCM,data:zycVyWyMQMCkZFvK5zKcLIRsnHrCoSB3/ogxb5YHhGWN9g==,iv:IPlWq7nqTgQzZSBsPu1asKY0E8p8zNAh3KGreFFoCcQ=,tag:kMyybckuo1k8XoxPTR1OZw==,type:comment]
#ENC[AES256_GCM,data:3t43YkdwjBQvVIT8j0mou+VuglmIXgD2Q7LG9Q8nOH0SJSCMeas1FFrFEqZ6eMG/YCas5aGQYd91XZAYBPoUZA==,iv:AEPo+gwCFqEpKgbxtP+QZnrSDYKA7Vcabd0+TGA4kfE=,tag:UwpIu/yvOemtzUVLDbxo+Q==,type:comment]
#ENC[AES256_GCM,data:ObEaweuLVICCLi2+tmop90GyX6H3tGddx3Bo6z8ikDRulCMK69IrtC8iF0FrDyaE0a6HZHKCdB4um+pC/Noya1rcNF8Vqw==,iv:j51v1NBSTHblDk/+rZ05/KzXq3joSbhMKq7lIr1oiNU=,tag:WQpD8VFLy1oPeO3I7BeUqg==,type:comment]
#ENC[AES256_GCM,data:QUYGQIWGCRBD2z2f3s4jDaK0WjwImv4MB9PUKwoStV3Ayv+ApA==,iv:TiRAuDVn7TTj5DLaaez2LBTp1JmyHpRfgJP5/jAVk3M=,tag:lsFqN1SUaYenQxNfIM6b+g==,type:comment]
apiVersion: ENC[AES256_GCM,data:oF4=,iv:hIa122cVFwHxnh32FSZUz5JiZD8IOpZA3KUhQh2mrgE=,tag:Me1Rhiv0jmYIBVY0S4GuUQ==,type:str]
kind: ENC[AES256_GCM,data:5a68xXUI,iv:iYZUvSD5FyXCO4ph3ngFRfEOg0NqrScNQ0XGyDp3+o8=,tag:lRJCAt4vc9q3XRIwOJ4Ccw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wX7HfQuDaM67qEo+JihXrJse+g==,iv:bXCl+XdQnp0ZGjaMeIdPyceTTUIc6VRAsYjuggUA2oI=,tag:AuDe8UcFpqfi3TWOgIhUPw==,type:str]
    namespace: ENC[AES256_GCM,data:2J1rAZa66CMx,iv:2hFk8YuVAeNRC2kLNzP9IGQGSwmUwcEHCbYxt4YvoiM=,tag:K1doM2AeIIaweuYe3RIXaA==,type:str]
type: ENC[AES256_GCM,data:7SCfME+k,iv:JvXK8+O9+WqzoXjerFjuCOR1gU0VyM4totwxjs24DTc=,tag:GQy5MMiaZ1Im9g2/bY20YA==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:0F+L4GVDBlBY,iv:gG8pdCRc0Z/gEQm4Bwh80JYdfCohIwctgER+P8rN9U8=,tag:Lq7cmIg51pbd4sSbD5PN+g==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:txLhMAf5hhm0,iv:tJUDAye+o2ki/v6Ks8sqhawL21r2f/0RfifxMLdr8Kk=,tag:nncX1+ibFrMfDSYYFX6Iqw==,type:str]
    #ENC[AES256_GCM,data:UMDiE1Vn2vbjUudVaukzag==,iv:yKvyJb8SLHNgcqV4QtFljp/B90N50F/+BaiqWIbNNCI=,tag:SnvhZ/8P0NPDXJFOJcvKow==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:OTTwFKr7shxS,iv:Ln2ZTD/fYnVv8x51RP0Gv3hu+dbkan+7ec1SjWJQkk8=,tag:uat0pg4XCYs6X8DC0GkdpA==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBd2ZyOW5YYmNIblVBTDZS
            WldMdzdoeFNJZ2JNNE1vWGlpQXlidHR5VDFRCnVpVHBTNmtKUERLTG9ZY3VFVGU2
            eXVBMXBIS0t2c1A1dkk4VDRSMzI0QUkKLS0tIHhJRmRPOUo3cHRzNzFmM1Rublc3
            aGc2L1AwVXpacUZyZUdoRUhzRTIvVHcK076tOyDJUZOsBIR97hFCWqNwe2sCM+Gm
            BX42cikGzqchBUVWLqy/ewTwQYHkaKIda/N1o+qNCqGYm2Ww6tE3qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T19:10:21Z"
    mac: ENC[AES256_GCM,data:P202oZRA09iPlT9unCPC3fFPEnuEI8d+otPltEX6a7wq8Fz9Om6OHytMY+Dq/6k3tUS+OuIU5TyKn7GDIyQShbmhDioAou63DX/Z+liVsu6cVw3ZN+8NDGjApq/hZoTwosHqex5UmGWx4xGGkF07Uc6Fwyscu4YtRYdNJcMLNBY=,iv:2/FpsXXYcWbScY94aYrUZy/A16TYgEc9dX10prOXHVk=,tag:EcUWGOmFW3boHLuqLmnriA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
#ENC[AES256_GCM,data:9PUdzuw0MdAUZX+uXM63MshHselpjLv8E97SyCt0o4VUK34G3lS8T2M=,iv:88lxXaBVmG5tiJlHqCcHtJRGalL3ps48GZLIFQRj4Hw=,tag:zvih/kx40mDxycT3D9Stxg==,type:comment]
apiVersion: ENC[AES256_GCM,data:ihw=,iv:44PFXy2Q34NGziNcNNhO+90IrAc1PMWYirq7xuTwXd0=,tag:03ldz1JAwiMuyKxpu5aeCw==,type:str]
kind: ENC[AES256_GCM,data:/ODQrJQt,iv:4nCzULABF4Dbm/i+S3qTVNz3MyXM/Mn6nn9xgqGhxKo=,tag:7+A8sMMXXmGACX9eHNszxg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:U9+dVE9ElyLzbRH7Rd4Bmg==,iv:D1Zjq8v2nqJWBbWAWOEd9UqnZwE3RzoBSYzfcnlFGYk=,tag:0zRvm+WeCimm4ZBPKg969A==,type:str]
    namespace: ENC[AES256_GCM,data:B9EDmRR0jyHs,iv:LP20w9zaFyvF4BPvyiRT4ef8LE/gSPeoGnDWxOSGUA8=,tag:yJdOkCYCsPbGNf5oK7eBtg==,type:str]
type: ENC[AES256_GCM,data:mebLJaZr,iv:yS4TbGjw9xPsVJ4h1QZC7gM7Gw2FhbZ50Hb7Wgbw7o4=,tag:EcBJ+fgJANeIqX8IbLV38g==,type:str]
stringData:
    #ENC[AES256_GCM,data:b+nvxT+6fEHmy3lFy0+1ow==,iv:m0RS+MqywLdviKv0PU9cTBvdCt9hZF95/xy5QSfwnro=,tag:avIHBchkCSIgTXlld9AQBw==,type:comment]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:lLJOl8K8as9T,iv:GL2EgP021eLTfvR29pIvu8YYAuhf3IDAXyE9F/FqLh4=,tag:X4FXAEYRlGWaXCzmPErflg==,type:str]
    #ENC[AES256_GCM,data:w3hYzXnHRT+qvxAVSdbLuB4Ai3kSPW1ZIWvZMFRK9aZ33Uka65Na,iv:pmqC8nwgApoJP+JdHTsTcrNg52r5TicbQwWL9vA8KlM=,tag:8kCvBdBOZDVODpUmOvGRkg==,type:comment]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:nPJAiVrhc3hr,iv:YsT15Z7gKwh4X/YDqTLLD7nSORg1Ox/fExX+aFlcSQo=,tag:NZg0t6M0F8PYSp8+oYCY0w==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:XEE21x0=,iv:sPhLn/q7VTAGWKi0PB5kcfCxqpARaZibAD4bGMsUMAo=,tag:IMWku4qEEqnR5ivIR+Kq5Q==,type:str]
    #ENC[AES256_GCM,data:nho9nrf6VfA3tAcBP/08AQ==,iv:fhOmxW1tYiukqre8F49190F6yprALo2bUx+vfUNF61g=,tag:SveROfjpLwyRZ/lukCJKHQ==,type:comment]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:5Tx0c8ljBNw+,iv:hbrZgu4nsqZW9k1pa1PO466kL8kWjjqjzYunxnBBklo=,tag:PZ71ZHyRd2+8xLayBYfIMw==,type:str]
    #ENC[AES256_GCM,data:gQB19aELKTm3KYLbaptgqQ==,iv:zS8fTs+tzdodwqrAx/DxEYCC9s7ZPX785NPKYbjimCk=,tag:m1DFZQPaZcj4dA/q8ogdoQ==,type:comment]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:p4ytJy/KLOk5jhbh4Go1,iv:WGHUQjT1cDzlz3vFdooEDBf5x1NZevfCtPiNGYg3NME=,tag:atc8JK5Y3+z79Bo/eMCrWw==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBd2ZyOW5YYmNIblVBTDZS
            WldMdzdoeFNJZ2JNNE1vWGlpQXlidHR5VDFRCnVpVHBTNmtKUERLTG9ZY3VFVGU2
            eXVBMXBIS0t2c1A1dkk4VDRSMzI0QUkKLS0tIHhJRmRPOUo3cHRzNzFmM1Rublc3
            aGc2L1AwVXpacUZyZUdoRUhzRTIvVHcK076tOyDJUZOsBIR97hFCWqNwe2sCM+Gm
            BX42cikGzqchBUVWLqy/ewTwQYHkaKIda/N1o+qNCqGYm2Ww6tE3qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T19:10:21Z"
    mac: ENC[AES256_GCM,data:P202oZRA09iPlT9unCPC3fFPEnuEI8d+otPltEX6a7wq8Fz9Om6OHytMY+Dq/6k3tUS+OuIU5TyKn7GDIyQShbmhDioAou63DX/Z+liVsu6cVw3ZN+8NDGjApq/hZoTwosHqex5UmGWx4xGGkF07Uc6Fwyscu4YtRYdNJcMLNBY=,iv:2/FpsXXYcWbScY94aYrUZy/A16TYgEc9dX10prOXHVk=,tag:EcUWGOmFW3boHLuqLmnriA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
