apiVersion: ENC[AES256_GCM,data:67s=,iv:OZZ0+8v2DdHpC1ZczayybgumqSBW8rQPA28Wx90oJzA=,tag:QwKGI8UNYdehEHaarSDN7A==,type:str]
kind: ENC[AES256_GCM,data:yv1Q9TAU,iv:XAQ2Rk7ZE53CXJkE3d3q2NswUMofOv1Jwr9RlSWMERs=,tag:yb/WUzS50MnuOy/d2356XQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:reodXpzyKbALW1iH/Hz6NA==,iv:fLKb6lMbv69wuJvKmyMScK+RAtsPIzL7CzEGzkm00go=,tag:OfjdBIpFlJZ4BkyQkLvrTQ==,type:str]
    namespace: ENC[AES256_GCM,data:dNNgHyH+WrI=,iv:1RjuWmyoQjjTsquC54mC7uWeSOnK3fCH8aiDMrkMwPU=,tag:poZUW36MUW0TKgnmjOsw1w==,type:str]
type: ENC[AES256_GCM,data:Yu+58C3y,iv:cEY8FMxNAW4o7WbEG8tn7b1kxknzEgCyhJIMtFfNPnI=,tag:0Al5psz1sfRbQhQdAYveMw==,type:str]
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:xVzMxfxmA9agdFoD3sm1/91MYGR7HnVxjXjqP5PRGNZdRGMzWI0/T9bExtk=,iv:cziBtUtHutYaBrhBRxockEELI8VDU3moUzDs6JZz9M4=,tag:8xJIHAWp8ddoM6bXI1cmUw==,type:str]
sops:
    age:
        - recipient: age1cmm4wtftqdxwfp6yrc4sgsgzmwx3zqhzwht8jgvqvwvxncn7qdmq03tp3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eW52Vno0MXFraEY0RE1W
            YTM5bStOTzQ3WkxDQzZnREpNcHNWMC9nL1E4CjJpZU9BNVEvUHlPSVd2ZWxRaTZo
            aDNlSm9udGtWTDlqZXRXS0RaVWN1UFUKLS0tIE4yV1hadU9kNWZyZlE0cEo4K2tP
            YVEwbXB0VThkWXhmM2ZHY1JYS0JoK3MKxiv82iqT+iVYOrMWOS/w64irley2UeX8
            S2ZIxNKRogoUeeBz3meHywF30IvJ4bx+2ZnX1UcSesHhBS/ZXtyvDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T00:05:23Z"
    mac: ENC[AES256_GCM,data:NuZwhpgKINXTaYfUr4Qfsohx/H+9OdcoOxPlz1CFL/+pxGmXMNDphDoPhNwlUZ0iDh6qmlYEN5d4HCNdCoXQn1ETmQKfutntM3eB5dM3dfW0AyZ823u8cDYGID3Hkl7zmOrN293EMaQqowhlKnjEJECTLrIeFYUghpCkgnWva9M=,iv:z0/U7hvkyaWvEEgV0GjT7jE79kk3RXC/fFsOc4EHv2s=,tag:uD3F2nihm8YW8ReukxeMRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
